"""
Auto-generated pytest test for QAID 755618

Original DSL: ../testcase/ips/topology1/755618.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__755618(testbed):
    """
    Verify SERVER: ips can detect predefined signature for http traffic. Good utm and traffic log
    
    QAID: 755618
    """
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("comment Create ips sensor to detect eicar and add this sensor to firewall proxy-policy")
        helper_govdom1(fgt_b)
        fgt_b.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action pass
    next
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        fgt_b.execute("""
    config firewall proxy-policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    set profile-protocol-options "default"
    next
    end
        """)
        fgt_b.execute("diag ips session clear")
        fgt_b.execute("diag sys session clear")
        fgt_b.execute("exe log delete-all")
        fgt_b.execute("sleep FGT_A:SLEEP_TIMER")
        fgt_b.execute("comment Clear wad statistics")
        fgt_b.execute("sleep 5")
        helper_outvdom(fgt_b)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment Download eicar via http")
        pc_01.execute("wget -t 1 -T 5 http://PC_02:DESTINATION1/virus/eicar")
        pc_01.execute("sleep 15").expect('100%', qaid="755618")
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("comment Check IPS log and then change action on signature to block")
        helper_govdom1(fgt_b)
        fgt_b.execute("diag ips session clear")
        fgt_b.execute("diag sys session clear")
        fgt_b.execute("sleep 5")
        fgt_b.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_b.execute("exe log filter category 4")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 5").expect('detected(.*?)Eicar.Virus.Test.File', qaid="755618")
        fgt_b.execute("exe log filter category 0")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 5").expect('service=\\"HTTP(.*?)utmaction=\\"allow(.*?)countips=1', qaid="755618")
        fgt_b.execute("exe log delete-all")
        fgt_b.execute("sleep 3")
        fgt_b.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action block
    next
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        fgt_b.execute("sleep FGT_A:SLEEP_TIMER")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment Download eicar via http")
        pc_01.execute("wget -t 1 -T 5 http://PC_02:DESTINATION1/virus/eicar")
        pc_01.execute("sleep 15").expect('403 Forbidden|503 ERROR', qaid="755618")
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("comment Check IPS log and then change action on signature to reset")
        helper_govdom1(fgt_b)
        fgt_b.execute("diag ips session clear")
        fgt_b.execute("diag sys session clear")
        fgt_b.execute("sleep 5")
        fgt_b.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_b.execute("exe log filter category 4")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 5").expect('dropped(.*?)Eicar.Virus.Test.File', qaid="755618")
        fgt_b.execute("exe log filter category 0")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 5").expect('service=\\"HTTP(.*?)utmaction=\\"block(.*?)countips=1', qaid="755618")
        fgt_b.execute("exe log delete-all")
        fgt_b.execute("sleep 3")
        fgt_b.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action reset
    next
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        fgt_b.execute("sleep FGT_A:SLEEP_TIMER")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment Download eicar via http")
        pc_01.execute("wget -t 1 -T 5 http://PC_02:DESTINATION1/virus/eicar")
        pc_01.execute("sleep 15").expect('403 Forbidden|503 ERROR', qaid="755618")
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("comment Check IPS log")
        helper_govdom1(fgt_b)
        fgt_b.execute("diag ips session clear")
        fgt_b.execute("diag sys session clear")
        fgt_b.execute("sleep 5")
        fgt_b.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_b.execute("exe log filter category 4")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 3").expect('reset(.*?)Eicar.Virus.Test.File', qaid="755618")
        fgt_b.execute("exe log filter category 0")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 3").expect('service=\\"HTTP(.*?)utmaction=\\"reset(.*?)countips=1', qaid="755618")
        fgt_b.execute("comment Clean up environment")
        fgt_b.execute("""
    config firewall proxy-policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_b.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        helper_outvdom(fgt_b)
        fgt_b.execute("report 755618")

    # All assertions tracked under QAID 755618
    testbed.results.report("755618")
