"""
Auto-generated pytest test for QAID 781994

Original DSL: ../testcase/ips/topology1/781994.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__781994(testbed):
    """
    Verify ips can detected/block/reset predefined signature for HTTP POST  and PUT method
    
    QAID: 781994
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Configure IPS sensor and explicit web-proxy")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action pass
    set log enable
    set rule 29844
    set status enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config web-proxy global
    set proxy-fqdn "default.fqdn"
    end
        """)
        fgt_a.execute("""
    config web-proxy explicit
    set status enable
    set ipv6-status enable
    end
        """)
        fgt_a.execute("""
    config ftp-proxy explicit
    set status enable
    end
        """)
        fgt_a.execute("""
    config system interface
    edit PORT2
    set explicit-web-proxy enable
    set explicit-ftp-proxy enable
    next
    end
        """)
        fgt_a.execute("""
    config firewall proxy-policy
    edit 1
    set proxy explicit-web
    set dstintf "PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set service "webproxy"
    set action accept
    set schedule "always"
    set utm-status enable
    set ips-sensor "sensor-1"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set nat enable
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 35")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("curl -x FGT_A:INT_IP:8080 -v http://PC_02:DESTINATION1 -m 18")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute('curl -x 10.1.100.1:8080 -v -F "f1=@/home/tester/ips/attack_scripts/eicar.1" httpbin.org/post')
        pc_02.execute("sleep 18").expect(' We are completely uploaded and fine', qaid="781994")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('detected(.*?)Eicar.Virus.Test.File', qaid="781994")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("sleep 30")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("curl -x FGT_A:INT_IP:8080 -v http://PC_02:DESTINATION1 -m 18")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute('curl -x 10.1.100.1:8080 -v -X PUT -F "f1=@/home/tester/ips/attack_scripts/eicar.1" httpbin.org/post')
        pc_02.execute("sleep 18").expect('Your attempt to access the Internet resource is blocked by Intrusion Prevention', qaid="781994")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?)Eicar.Virus.Test.File', qaid="781994")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action reset
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("sleep 30")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("curl -x FGT_A:INT_IP:8080 -v http://PC_02:DESTINATION1 -m 18")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute('curl -x 10.1.100.1:8080 -v -X PUT -F "f1=@/home/tester/ips/attack_scripts/eicar.1" httpbin.org/post')
        pc_02.execute("sleep 18").expect('Your attempt to access the Internet resource is blocked by Intrusion Prevention', qaid="781994")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('reset(.*?)Eicar.Virus.Test.File', qaid="781994")
        fgt_a.execute("""
    config firewall proxy-policy
    delete 1
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config ips custom
    purge
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set nat disable
    next
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 781994")

    # All assertions tracked under QAID 781994
    testbed.results.report("781994")
