"""
Auto-generated pytest test for QAID 877245

Original DSL: ../testcase/ips/topology1/877245.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_goglobal import helper_goglobal


# ===== Test Function =====

def test__877245(testbed):
    """
    877245 Verify that IPS sensor can block/monitor connections to Botnet IPs
    
    QAID: 877245
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-botnet"
    set scan-botnet-connections block
    next
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-botnet"
    set ssl-ssh-profile "new-deep-inspection"
    set nat enable
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("dia sys botnet-ip flush")
        fgt_a.execute("dia sys botnet-ip list 0 50 | grep 'port=80-80'")
        fgt_a.execute('setvar -e "ip=(.*?)-" -to IPADDR')
        fgt_a.execute("dia sys botnet-ip list 0 50 | grep 'port=80-80'")
        fgt_a.execute('setvar -e "botnet=(.*?), hit_count" -to RULEID')
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 172.16.200.55/index.html")
        pc_01.execute("sleep 25")
        pc_01.execute("clear_buffer")
        pc_01.execute(f"curl -v http://{pc_01.testbed.env.get_dynamic_var('IPADDR')} -m 5")
        pc_01.execute("sleep 6").expect('Connection timed out', qaid="877245")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 10")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 2").expect('eventtype=\\"botnet(.*?)msg=\\"Botnet C&C Communication', qaid="877245")
        fgt_a.execute(f'varexpect -v "{fgt_a.testbed.env.get_dynamic_var('IPADDR')}" -for 877246 -t 5').expect('action=\\"dropped(.*?)service=\\"HTTP', qaid="877245")
        fgt_a.execute(f'varexpect -v "{fgt_a.testbed.env.get_dynamic_var('RULEID')}" -for 877246 -t 5')
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 2").expect('action=\\"timeout(.*?)service=\\"HTTP(.*?)utmaction=\\"block(.*?)countips=1(.*?)utmref', qaid="877245")
        fgt_a.execute("exe log delete-all")
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-botnet"
    set scan-botnet-connections monitor
    next
    end
        """)
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 172.16.200.55/index.html")
        pc_01.execute("sleep 25")
        pc_01.execute("clear_buffer")
        pc_01.execute(f"curl -v http://{pc_01.testbed.env.get_dynamic_var('IPADDR')} -m 5")
        pc_01.execute("sleep 6").expect('Operation timed out|Connection timed out|200 OK|Connection refused|404 Not Found', qaid="877245")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 10")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 2").expect('eventtype=\\"botnet(.*?)msg=\\"Botnet C&C Communication', qaid="877245")
        fgt_a.execute(f'varexpect -v "{fgt_a.testbed.env.get_dynamic_var('IPADDR')}" -for 877246 -t 5').expect('action=\\"detected(.*?)service=\\"HTTP', qaid="877245")
        fgt_a.execute(f'varexpect -v "{fgt_a.testbed.env.get_dynamic_var('RULEID')}" -for 877246 -t 5')
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 2").expect('service=\\"HTTP(.*?)utmaction=\\"allow(.*?)countips=1(.*?)utmref', qaid="877245")
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("dia sys botnet-ip hit")
        fgt_a.execute("sleep 2").expect('proto=TCP(.*?)ip={$IPADDR}(.*?)port=80(.*?)botnet={$RULEID}(.*?)hit_count=2', qaid="877245")
        fgt_a.execute("dia sys botnet-ip flush")
        fgt_a.execute("dia sys botnet-ip hit").expect('The number of hit entries: 0', qaid="877245")
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-botnet"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 877245")
        fgt_a.execute("report 877246")
        fgt_a.execute("report 877247")
        fgt_a.execute("report 877980")

    # All assertions tracked under QAID 877245
    testbed.results.report("877245")
