"""
Auto-generated pytest test for QAID 751047

Original DSL: ../testcase/ips/topology1/751047.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_goglobal import helper_goglobal


# ===== Test Function =====

def test__751047(testbed):
    """
    Verify inline SSL inspection work for flow-AV/DLP/Webfilter
    
    QAID: 751047
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment enable flow av/dlp/webfilter on firewall policy")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config webfilter profile
    edit "web-filter-flow"
    config ftgd-wf
    config filters
    edit 25
    set category 25
    set action block
    next
    end
        """)
        fgt_a.execute("end")
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config webfilter urlfilter
    edit 1
    config entries
    edit 3
    set url "www.facebook.com"
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set srcintf "PORT2"
    set dstintf "PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set action accept
    set schedule "always"
    set service "ALL"
    set utm-status enable
    set av-profile "AV-flow"
    set webfilter-profile "web-filter-flow"
    set dlp-profile "flow-dlp"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    set nat enable
    next
    end
        """)
        fgt_a.execute("diag ips raw clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 30")
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("dia test application urlfilter 99")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 5 -S https://PC_02:DESTINATION1/virus/eicar --no-check-certificate")
        pc_02.execute("sleep 22").expect('Connection reset by peer', qaid="751047")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 2")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 10").expect('blocked(.*?)EICAR_TEST_FILE(.*?)AV-flow', qaid="751047")
        fgt_a.execute("exec log filter category 0")
        fgt_a.execute("exec log filter field subtype forward")
        fgt_a.execute("exec log display").expect('block(.*?)countav=1', qaid="751047")
        fgt_a.execute("exec log delete")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 18 -S https://PC_02:DESTINATION1/app_data/bar.exe --no-check-certificate")
        pc_02.execute("sleep 22").expect('Connection reset by peer|Connection timed out', qaid="751047")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 9")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 10").expect('block(.*?)bar.exe(.*?)flow-dlp', qaid="751047")
        fgt_a.execute("exec log filter category 0")
        fgt_a.execute("exec log filter field subtype forward")
        fgt_a.execute("exec log display").expect('block(.*?)countdlp=1', qaid="751047")
        fgt_a.execute("exec log delete")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("curl -v -k -4 https://PC_02:DESTINATION1 -m 20")
        pc_02.execute("sleep 22")
        pc_02.execute("clear_buffer")
        pc_02.execute("curl -v -k -4  https://www.youtube.com -m 20")
        pc_02.execute("sleep 22").expect('Web Page Blocked|OpenSSL SSL_read: SSL_ERROR_SYSCALL|SSL_write(.*?)errno', qaid="751047")
        pc_02.execute("curl -v -k -4  https://www.facebook.com -m 20")
        pc_02.execute("sleep 22").expect('Web Page Blocked', qaid="751047")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session filter src PC_02:IP_ETH1")
        fgt_a.execute("dia sys session list")
        fgt_a.execute("sleep 10")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 3")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 10").expect('urlfilter(.*?)web-filter-flow(.*?)www.facebook.com(.*?)blocked', qaid="751047")
        fgt_a.expect('ftgd_blk(.*?)www.youtube.com(.*?)web-filter-flow(.*?)blocked(.*?)Streaming Media and Download', qaid="751047")
        fgt_a.execute("exec log filter category 0")
        fgt_a.execute("exec log filter field subtype forward")
        fgt_a.execute("exec log display")
        fgt_a.execute("sleep 5").expect('block(.*?)countweb', qaid="751047")
        fgt_a.expect('block(.*?)countweb', qaid="751047")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    set nat disable
    next
    end
        """)
        fgt_a.execute("""
    config webfilter urlfilter
    edit 1
    config entries
    delete 3
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config webfilter profile
    edit "web-filter-flow"
    config ftgd-wf
    config filters
    delete 25
    end
        """)
        fgt_a.execute("end")
        fgt_a.execute("next")
        fgt_a.execute("end")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 751047")

    # All assertions tracked under QAID 751047
    testbed.results.report("751047")
