"""
Auto-generated pytest test for QAID 205817

Original DSL: ../testcase/ips/topology1/205817.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__205817(testbed):
    """
    IPS Regression Test Case 2.6
    
    QAID: 205817
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_02_04:Busy: create custom signatures")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-temp"
    set comment "temp sensor for testing"
    config entries
    edit "1"
    set severity critical
    set protocol TCP
    set os Windows
    set status enable
    set log enable
    set action reset
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("show ips sensor sensor-temp").expect('os Windows', qaid="205817")
        fgt_a.execute("""
    config ips sensor
    delete "sensor-temp"
    end
        """)
        fgt_a.execute("clear_buffer")
        fgt_a.execute("show ips sensor").expect('sensor-temp', qaid="205817", should_fail=True)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 205817")

    # All assertions tracked under QAID 205817
    testbed.results.report("205817")
