"""
Auto-generated pytest test for QAID 749201

Original DSL: ../testcase/ips/topology1/749201.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__749201(testbed):
    """
    Verify ips-sensor monitor/block/reset/quarantine work in id-based policy
    
    QAID: 749201
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config user local
    edit "test"
    set type password
    set passwd PC_05:PASSWORD
    next
    end
        """)
        fgt_a.execute("""
    config user setting
    set auth-type http https ftp telnet
    end
        """)
        fgt_a.execute("""
    config ips custom
    edit "match small"
    set signature "F-SBID( --attack_id 5835;  --name \"match small\"; --default_action reset; --service http; --protocol tcp; --pattern \"small\"; --severity info; --status disable; )"
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 5835
    set status enable
    set action pass
    next
    edit 2
    set rule 29844
    set status enable
    set action block
    next
    edit 3
    set rule 31129
    set status enable
    set action reset
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    set users "test"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute('mytelnet -d pc -u test -p PC_05:PASSWORD -ip PC_02:DESTINATION1 -e "successful" -for 749201 -t 15')
        pc_01.execute("clear_buffer")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia firewall auth list")
        fgt_a.execute("sleep 2").expect('PC_01:IP_ETH1', qaid="749201")
        fgt_a.expect('test', qaid="749201")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 -S --delete-after PC_02:DESTINATION1")
        pc_01.execute("sleep 25")
        pc_01.execute("clear_buffer")
        pc_01.execute("wget -t 1 -T 10 -S --delete-after PC_02:DESTINATION1/ips_data/text")
        pc_01.execute("sleep 15").expect('100%', qaid="749201")
        pc_01.execute("wget -t 1 -T 10 -S --delete-after PC_02:DESTINATION1/ips_data/1.mp4")
        pc_01.execute("sleep 15").expect('Connection reset by peer', qaid="749201")
        pc_01.execute("curl -vk -m 15 https://PC_02:DESTINATION1/virus/eicar")
        pc_01.execute("sleep 15").expect('timed out', qaid="749201")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("dia firewall auth clear")
        fgt_a.execute("sleep 15")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('action=\\"dropped\\"(.*?)service=\\"HTTPS\\"(.*?)attackid=29844(.*?)user=\\"test\\"(.*?)file_transfer: Eicar.Virus.Test.File', qaid="749201")
        fgt_a.expect('action=\\"reset\\"(.*?)service=\\"HTTP\\"(.*?)attackid=31129(.*?)user=\\"test\\"(.*?)applications3: Adobe.Flash.MP4.Atoms.Invalid.Length.Memory.Corruption', qaid="749201")
        fgt_a.expect('action=\\"detected\\"(.*?)service=\\"HTTP\\"(.*?)attackid=5835(.*?)user=\\"test\\"(.*?)custom: match small', qaid="749201")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter field dstip PC_02:DESTINATION1")
        fgt_a.execute("exe log display").expect('user=\\"test\\"(.*?)utmaction=\\"reset\\"(.*?)countips=1', qaid="749201")
        fgt_a.execute("exe log display").expect('user=\\"test\\"(.*?)utmaction=\\"block\\"(.*?)countips=1', qaid="749201")
        fgt_a.execute("exe log display").expect('user=\\"test\\"(.*?)utmaction=\\"allow\\"(.*?)countips=1', qaid="749201")
        fgt_a.execute("""
    config application list
    edit "app-list-1"
    set other-application-log enable
    config entries
    edit 1
    set category 5
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    unset ips-sensor
    set application-list "app-list-1"
    set users "test"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute('mytelnet -d pc -u test -p PC_05:PASSWORD -ip PC_02:DESTINATION1 -e "successful" -for 749201 -t 15')
        pc_01.execute("clear_buffer")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia firewall auth list")
        fgt_a.execute("sleep 2").expect('PC_01:IP_ETH1', qaid="749201")
        fgt_a.expect('test', qaid="749201")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 -S --delete-after PC_02:DESTINATION1")
        pc_01.execute("sleep 25")
        pc_01.execute("clear_buffer")
        pc_01.execute("curl -v PC_02:DESTINATION1/app_data/story.mp3 -m 10")
        pc_01.execute("sleep 15").expect('Application Blocked', qaid="749201")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter category 10")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('user=\\"test\\"(.*?)service=\\"HTTP\\"(.*?)applist=\\"app-list-1\\"(.*?)action=\\"block\\"(.*?)Video\\/Audio: HTTP.Audio', qaid="749201")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3")
        fgt_a.execute("dia firewall auth clear")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    unset users
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-1"
    end
        """)
        fgt_a.execute("""
    config application list
    del "app-list-1"
    end
        """)
        fgt_a.execute("""
    config user local
    del "test"
    end
        """)
        fgt_a.execute("""
    config user setting
    unset auth-type
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 749201")
        fgt_a.execute("report 816006")

    # All assertions tracked under QAID 749201
    testbed.results.report("749201")
