"""
Auto-generated pytest test for QAID 206036

Original DSL: ../testcase/ips/topology1/206036.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__206036(testbed):
    """
    IPS Regression Test Case 21.1
    
    QAID: 206036
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_21.1:Busy: enable interface-policy6 on incoming interface")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    next
    end
        """)
        fgt_a.execute("""
    config firewall interface-policy6
    edit 1
    set interface PORT2
    set srcaddr6 "all"
    set dstaddr6 "all"
    set service6 "ALL"
    set ips-sensor-status enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("show firewall interface-policy6").expect('ips-sensor-status enable', qaid="206036")
        fgt_a.execute("""
    config firewall interface-policy6
    delete 1
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 206036")

    # All assertions tracked under QAID 206036
    testbed.results.report("206036")
