"""
Auto-generated pytest test for QAID 729766

Original DSL: ../testcase/ips/topology1/729766.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__729766(testbed):
    """
    IPS Regression Test Case 21.8
    
    QAID: 729766
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_21.8:Busy: enable interface-policy6 on incoming interface")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "match small"
    set comment ''
    set signature "F-SBID( --attack_id 5835;  --name \"match small\"; --default_action reset; --service http; --protocol tcp; --pattern \"small\"; --severity info; --status disable; )"
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-11"
    config entries
    purge
    edit 1
    set action pass
    set log-packet enable
    set rule 29844
    set status enable
    next
    edit 2
    set action reset
    set log-packet enable
    set rule 5835
    set status enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 11
    set srcintf "PORT2"
    set dstintf "PORT1"
    set srcaddr6 "all"
    set dstaddr6 "all"
    set action accept
    set utm-status enable
    set schedule "always"
    set service "ALL"
    set ips-sensor "sensor-11"
    set profile-protocol-options "default"
    next
    end
        """)
        fgt_a.execute("diag ips raw clear")
        fgt_a.execute("diag sys session6 clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -6 -t 1 -T 20 -S --delete-after http://[PC_05:IP6_ETH1]/index.html")
        pc_02.execute("sleep 30")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -6 -t 1 -T 20 -S --delete-after http://[PC_05:IP6_ETH1]/ips_data/text")
        pc_02.execute("sleep 10").expect('Connection reset by peer', qaid="729766")
        pc_02.execute("wget -6 -t 1 -T 20 -S --delete-after http://[PC_05:IP6_ETH1]/virus/eicar")
        pc_02.execute("sleep 10").expect('68/68', qaid="729766")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('detected(.*?)Eicar.Virus.Test.File', qaid="729766")
        fgt_a.expect('reset', qaid="729766")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-11"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    delete 11
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 729766")

    # All assertions tracked under QAID 729766
    testbed.results.report("729766")
