"""
Auto-generated pytest test for QAID topology1-FGT_C

Original DSL: ../testcase/ips/topology1/topology1-FGT_C.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_purge import helper_purge
from helpers.helper_setupC import helper_setupC


# ===== Test Function =====

def test_topology1_FGT_C(testbed):
    """
    This is topology #1 for IPS regression test.
    
    QAID: topology1-FGT_C
    """
    with testbed.device('FGT_C') as fgt_c:
        fgt_c.execute("comment Topology1:Busy:Resetting Firewall FGTC")
        if fgt_c.testbed.read_env_variables('FGT_A:VM') == 'yes':
            pass
        else:
            fgt_c.execute("resetFirewall")
        fgt_c.execute("comment Topology1:Busy:Cleanning up environment for FGTC")
        helper_purge(fgt_c)
    with testbed.device('FGT_C') as fgt_c:
        fgt_c.execute("comment Topology1:Busy:Setting up environment for FGTC")
        helper_setupC(fgt_c)
    with testbed.device('FGT_C') as fgt_c:
        fgt_c.execute("show system global").expect('FGT-C', qaid="topology1-FGT_C")
        fgt_c.execute("report topology1-FGT_C")

    # All assertions tracked under QAID topology1-FGT_C
    testbed.results.report("topology1-FGT_C")
