"""
Auto-generated pytest test for QAID 895491

Original DSL: ../testcase/ips/topology1/895491.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__895491(testbed):
    """
    NGFW: Verify that custom IPS signature detection is good - FTP
    
    QAID: 895491
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "match small"
    set signature "F-SBID( --attack_id 5835;  --name \"match small\"; --default_action pass; --protocol tcp; --pattern \"small\"; --context file; --severity info; )"
    set comment ''
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "ips-ngfw"
    config entries
    edit 1
    set rule 5835
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall security-policy
    edit 99
    set utm-status enable
    set app-category 12 15
    set ips-sensor "ips-ngfw"
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 20 https://PC_02:DESTINATION1 --no-check-certificate")
        pc_02.execute("sleep 22")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 15 ftp://PC_02:DESTINATION1/pub/text")
        pc_02.execute("sleep 20").expect('Data connection: Connection timed out', qaid="895491")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep 3")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?)service=\\"FTP(.*?)policyid=99(.*?)attack=\\"match small(.*?)direction=\\"incoming\\"(.*?)ips-ngfw', qaid="895491")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 2").expect('policyid=99(.*?)policytype=\\"security-policy(.*?)utmaction=\\"block(.*?)countips=1', qaid="895491")
        fgt_a.execute("""
    config firewall security-policy
    edit 99
    unset ips-sensor
    unset app-category
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "ips-ngfw"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 895491")

    # All assertions tracked under QAID 895491
    testbed.results.report("895491")
