"""
Auto-generated pytest test for QAID 833690

Original DSL: ../testcase/ips/topology1/833690.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__833690(testbed):
    """
    Verify SERVER: wanopt policy have good utm and traffic-log for AppCtrl
    
    QAID: 833690
    """
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("comment Create application list to block HTTP.Audio and add this list to firewall policy")
        helper_govdom1(fgt_b)
        fgt_b.execute("""
    config application list
    edit "app-list-1"
    config entries
    edit 1
    set category 5
    next
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        fgt_b.execute("""
    config firewall proxy-policy
    edit 1
    set utm-status enable
    set application-list "app-list-1"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_b.execute("diag ips session clear")
        fgt_b.execute("diag sys session clear")
        fgt_b.execute("exe log delete-all")
        fgt_b.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_b)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 5 https://PC_02:DESTINATION1/app_data/story.mp3 --no-check-certificate")
        pc_01.execute("sleep 15").expect('403 Forbidden|503 ERROR', qaid="833690")
    with testbed.device('FGT_B') as fgt_b:
        helper_govdom1(fgt_b)
        fgt_b.execute("diag ips session clear")
        fgt_b.execute("diag sys session clear")
        fgt_b.execute("sleep 5")
        fgt_b.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_b.execute("exe log filter category 10")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 3").expect('HTTPS(.*?)app-list-1(.*?)block(.*?)HTTP.Audio', qaid="833690")
        fgt_b.execute("exe log filter category 0")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 3").expect('service=\\"HTTPS(.*?)utmaction=\\"block(.*?)countapp', qaid="833690")
        fgt_b.execute("""
    config application list
    edit "app-list-1"
    config entries
    edit 1
    unset category
    next
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        fgt_b.execute("""
    config firewall proxy-policy
    edit 1
    set utm-status disable
    next
    end
        """)
        helper_outvdom(fgt_b)
        fgt_b.execute("report 833690")

    # All assertions tracked under QAID 833690
    testbed.results.report("833690")
