"""
Auto-generated pytest test for QAID setupPC-wanopt

Original DSL: ../testcase/ips/topology1/setupPC-wanopt.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed


# ===== Test Function =====

def test_setupPC_wanopt(testbed):
    """
    Update PC_01/PC_02 IP address for NAT setup
    
    QAID: setupPC-wanopt
    """
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ip addr flush dev PC_01:ETH1")
        pc_01.execute("ip route flush dev PC_01:ETH1")
        pc_01.execute("ip addr flush dev PC_01:ETH2")
        pc_01.execute("ip route flush dev PC_01:ETH2")
        pc_01.execute("ip addr flush dev PC_01:VLAN100")
        pc_01.execute("ip route flush dev PC_01:VLAN100")
        pc_01.execute("ifconfig PC_01:ETH1 10.1.100.11 netmask 255.255.255.0 broadcast 10.1.100.255")
        pc_01.execute("route add default gw 10.1.100.1")
        pc_01.execute("sleep 5")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment Verify if networking between PC01 and PC05 is ok")
        pc_01.execute("ping -c 10 PC_01:DESTINATION1")
        pc_01.execute("sleep 20").expect('64 bytes', qaid="setupPC-wanopt")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ip addr flush dev PC_02:ETH1")
        pc_02.execute("ip route flush dev PC_02:ETH1")
        pc_02.execute("report setupPC_wanopt")

    # All assertions tracked under QAID setupPC-wanopt
    testbed.results.report("setupPC-wanopt")
