"""
Auto-generated pytest test for QAID 730278

Original DSL: ../testcase/ips/topology1/730278.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__730278(testbed):
    """
    IPS Regression Test Case IPS Explicit Proxy
    
    QAID: 730278
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_21.8:Busy: enable interface-policy6 on incoming interface")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action block
    set log-packet enable
    set rule 29844
    set status enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config web-proxy global
    set proxy-fqdn "default.fqdn"
    end
        """)
        fgt_a.execute("""
    config web-proxy explicit
    set status enable
    set ftp-over-http enable
    set pac-file-server-status enable
    set ipv6-status enable
    end
        """)
        fgt_a.execute("""
    config ftp-proxy explicit
    set status enable
    end
        """)
        fgt_a.execute("""
    config system interface
    edit PORT2
    set explicit-web-proxy enable
    set explicit-ftp-proxy enable
    next
    end
        """)
        fgt_a.execute("""
    config firewall proxy-policy
    edit 1
    set proxy explicit-web
    set dstintf "PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set service "webproxy"
    set action accept
    set schedule "always"
    set utm-status enable
    set ips-sensor "sensor-1"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("diag ips raw clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("curl -x FGT_A:INT_IP:8080 -v http://PC_05:IP_ETH1/virus/eicar")
        pc_02.execute("sleep 22").expect('blocked by Intrusion Prevention|blocked by IPS Sensor', qaid="730278")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 10").expect('dropped(.*?)dstport=80(.*?)direction=\\"incoming\\"(.*?)Eicar.Virus.Test.File', qaid="730278")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exec log filter field subtype forward")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 10").expect('utmref', qaid="730278")
        fgt_a.execute("""
    config firewall proxy-policy
    del 1
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 730278")

    # All assertions tracked under QAID 730278
    testbed.results.report("730278")
