"""
Auto-generated pytest test for QAID 729743

Original DSL: ../testcase/ips/topology1/729743.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__729743(testbed):
    """
    IPS Regression Test Case 21.8
    
    QAID: 729743
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_21.8:Busy: enable interface-policy6 on incoming interface")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action block
    set log-packet enable
    set quarantine attacker
    set quarantine-expiry 2m
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set srcintf "PORT2"
    set dstintf "PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set action accept
    set schedule "always"
    set service "ALL"
    set utm-status enable
    set ips-sensor "sensor-1"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    set nat enable
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 20 https://PC_05:IP_ETH1 --no-check-certificate")
        pc_02.execute("sleep 30")
        pc_02.execute("curl -4kv -m 15 https://PC_05:IP_ETH1/virus/eicar -O")
        pc_02.execute("sleep 30").expect('Operation timed out', qaid="729743")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('dropped(.*?)dstport=443(.*?)direction=\\"incoming\\"(.*?)Eicar.Virus.Test.File', qaid="729743")
        fgt_a.execute("dia user banned-ip list")
        fgt_a.execute("sleep 5").expect('PC_05:IP_ETH1 (.*?)IPS', qaid="729743")
        fgt_a.execute("sleep 130")
        fgt_a.execute("dia user banned-ip list").expect('PC_05:IP_ETH1', qaid="729743", should_fail=True)
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset ips-sensor
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 729743")

    # All assertions tracked under QAID 729743
    testbed.results.report("729743")
