"""
Auto-generated pytest test for QAID 735500

Original DSL: ../testcase/ips/topology1/735500.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_goglobal import helper_goglobal


# ===== Test Function =====

def test__735500(testbed):
    """
    Multilevel IPS:Verify  new CLI "config ips global"-> set database: extended and regular
    
    QAID: 735500
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Enable an IPS sensor on firewall policy")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set profile-protocol-options "default"
    set ips-sensor "g-default"
    next
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("comment Set database to regular")
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set database regular
    set engine-count 1
    end
        """)
        fgt_a.execute("""
    config ips global
    show full
        """).expect('set database regular', qaid="735500")
        fgt_a.execute("end")
        fgt_a.execute("sleep 60")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 25 PC_05:IP_ETH1")
        pc_02.execute("sleep 26")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 10 PC_05:IP_ETH1")
        pc_02.execute("sleep 15")
        pc_02.execute("clear_buffer")
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("dia test application ipsmonitor 1")
        fgt_a.execute("sleep 10").expect('database:(.*?)ipsdb', qaid="735500")
        fgt_a.execute("""
    config ips global
    set engine-count 0
    end
        """)
        fgt_a.execute("sleep 30")
        fgt_a.execute("comment Set database to extended")
        fgt_a.execute("""
    config ips global
    set database extended
    set engine-count 1
    end
        """)
        fgt_a.execute("""
    config ips global
    show full
        """).expect('set database extended', qaid="735500")
        fgt_a.execute("end")
        fgt_a.execute("sleep 60")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 25 PC_05:IP_ETH1")
        pc_02.execute("sleep 26")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 10 PC_05:IP_ETH1")
        pc_02.execute("sleep 15")
        pc_02.execute("clear_buffer")
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("dia test application ipsmonitor 1")
        fgt_a.execute("sleep 10").expect('database:(.*?)ipsetdb', qaid="735500")
        helper_outvdom(fgt_a)
        fgt_a.execute("comment Remove IPS sensor from firewall policy")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set engine-count 0
    end
        """)
        fgt_a.execute("sleep 60")
        fgt_a.execute("dia test application ipsmonitor 1")
        fgt_a.execute("sleep 10").expect('engine count =  1|engine count = 0(.*?)+1', qaid="735500")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 735500")

    # All assertions tracked under QAID 735500
    testbed.results.report("735500")
