"""
Auto-generated pytest test for QAID 205996

Original DSL: ../testcase/ips/topology1/205996.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__205996(testbed):
    """
    IPS Regression Test Case 17.1
    
    QAID: 205996
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_17_01:Busy: create custom signatures match_apache")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    purge
    edit small
    set signature "F-SBID( --name \"small\"; --attack_id 5835; --protocol tcp; --severity medium; --status disable; --service http; --pattern \"small\"; )"
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 5835
    set rule 5835
    set action block
    set status enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 20 -S --delete-after PC_05:IP_ETH1/index.html")
        pc_02.execute("sleep 30")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 20 -S --delete-after PC_05:IP_ETH1/ips_data/text")
        pc_02.execute("sleep 20").expect('timed out', qaid="205996")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped', qaid="205996")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    delete 5835
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config ips custom
    purge
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 205996")

    # All assertions tracked under QAID 205996
    testbed.results.report("205996")
