"""
Auto-generated pytest test for QAID topology1-nat

Original DSL: ../testcase/ips/topology1/topology1-nat.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_purge import helper_purge
from helpers.helper_enable import helper_enable
from helpers.helper_setupA_nat import helper_setupA_nat
from helpers.helper_initializeA_nat import helper_initializeA_nat


# ===== Test Function =====

def test_topology1_nat(testbed):
    """
    This is topology #1 for IPS regression test.
    
    QAID: topology1-nat
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Topology1:Busy:Resetting Firewall FGT_A")
        if fgt_a.testbed.read_env_variables('FGT_A:VM') == 'yes':
            pass
        else:
            fgt_a.execute("resetFirewall")
            fgt_a.execute("keep_running 0")
        fgt_a.execute("comment Topology1:Busy:Cleanning up environment for FGT_A")
        helper_purge(fgt_a)
        fgt_a.execute("sleep 10")
        fgt_a.execute("comment Topology1:Busy:Creating vdoms for FGT_A")
        helper_enable(fgt_a)
        fgt_a.execute("sleep 10")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Topology1:Busy:Setting up environment for FGTA")
        helper_setupA_nat(fgt_a)
        helper_initializeA_nat(fgt_a)
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("forcelogin")
        fgt_b.execute("comment Topology1:Busy:Resetting Firewall FGT_B")
        if fgt_b.testbed.read_env_variables('FGT_B:VM') == 'yes':
            pass
        else:
            fgt_b.execute("resetFirewall")
            fgt_b.execute("keep_running 0")
        fgt_b.execute("""
    config system interface
    edit "fortilink"
    unset member
    next
    end
        """)
        if fgt_b.testbed.read_env_variables('FGT_B:Model') == 'FGT_101F':
            fgt_b.execute("""
    config system virtual-switch
    edit "lan"
    config port
    delete "FGT_A:PORT5"
    end
            """)
            fgt_b.execute("next")
            fgt_b.execute("end")
        elif fgt_b.testbed.read_env_variables('FGT_B:Model') == 'FGT_61F':
            fgt_b.execute("""
    config system virtual-switch
    edit "internal"
    config port
    delete "FGT_A:PORT5"
    end
            """)
            fgt_b.execute("next")
            fgt_b.execute("end")
        else:
            pass
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ip route change default via PC_01:GATEWAY1")
        pc_01.execute("sleep 5")
        pc_01.execute("ip -6 addr flush dev PC_01:ETH1")
        pc_01.execute("ip -6 route flush dev PC_01:ETH1")
        pc_01.execute("ifconfig PC_01:ETH1 PC_01:IP_ETH1 netmask 255.255.255.0 broadcast 10.1.100.255")
        pc_01.execute("route add default gw FGT_A:INT_IP")
        pc_01.execute("ifconfig PC_01:ETH1 inet6 add 2000:10:1:100::11/64")
        pc_01.execute("ip -6 route add 2000:172:16:200::0/64 via 2000:10:1:100::1")
        pc_01.execute("ip -6 route")
        pc_01.execute("sleep 10")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ip route change default via PC_02:GATEWAY")
        pc_02.execute("sleep 5")
        pc_02.execute("ip -6 addr flush dev PC_02:ETH1")
        pc_02.execute("ip -6 route flush dev PC_02:ETH1")
        pc_02.execute("ifconfig PC_02:ETH1 PC_02:IP_ETH1 netmask 255.255.255.0 broadcast 10.1.100.255")
        pc_02.execute("route add default gw FGT_A:INT_IP")
        pc_02.execute("ifconfig PC_02:ETH1 inet6 add 2000:10:1:100::22/64")
        pc_02.execute("ip -6 route add 2000:172:16:200::0/64 via 2000:10:1:100::1")
        pc_02.execute("ip -6 route")
        pc_02.execute("sleep 10")
    with testbed.device('PC_05') as pc_05:
        pc_05.execute("ip -6 addr flush dev PC_05:ETH1")
        pc_05.execute("ip -6 route flush dev PC_05:ETH1")
        pc_05.execute("ifconfig PC_05:ETH1 inet6 add 2000:172:16:200::55/64")
        pc_05.execute("ip -6 route add 2000:10:1:100::0/64 via FGT_A:IPV6_EXT_IP")
        pc_05.execute("sleep 2")
        pc_05.execute("ifconfig")
        pc_05.execute("sleep 5").expect('55', qaid="topology1-nat")
        pc_05.execute("route -n -A inet6")
        pc_05.execute("sleep 5").expect('200', qaid="topology1-nat")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment Verify if networking between PC01 and PC05 is ok")
        pc_01.execute("ping -c 10 172.16.200.55")
        pc_01.execute("sleep 20").expect('64 bytes', qaid="topology1-nat")
        pc_01.execute("ping6 -c 10 2000:172:16:200::55")
        pc_01.execute("sleep 20").expect('64 bytes', qaid="topology1-nat")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("comment Verify if networking between PC02 and PC05 is ok")
        pc_02.execute("ping -c 10 172.16.200.55")
        pc_02.execute("sleep 20").expect('64 bytes', qaid="topology1-nat")
        pc_02.execute("ping6 -c 10 2000:172:16:200::55")
        pc_02.execute("sleep 20").expect('64 bytes', qaid="topology1-nat")
        pc_02.execute("report topology1-nat")

    # All assertions tracked under QAID topology1-nat
    testbed.results.report("topology1-nat")
