"""
Auto-generated pytest test for QAID 947032

Original DSL: ../testcase/ips/topology1/947032.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__947032(testbed):
    """
    947032: Verify IPS traffic with specific CVE id can be detected/blocked properly
    
    QAID: 947032
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit  "cve"
    config entries
    edit 1
    set cve "CVE-2012-0754"
    set status enable
    set log-packet enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "cve"
    set ssl-ssh-profile "new-deep-inspection"
    set nat enable
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("dia ips ssl clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 -S --delete-after http://PC_02:DESTINATION1/index.html")
        pc_01.execute("sleep 30")
        pc_01.execute("clear_buffer")
        pc_01.execute("curl -v http://PC_02:DESTINATION1/ips_data/1.mp4 -m 15")
        pc_01.execute("sleep 20").expect('Operation timed out', qaid="947032")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display").expect('action=\\"dropped(.*?)service=\\"HTTP(.*?)dstport=80(.*)direction=\\"incoming(.*?)Adobe.Flash.MP4.Atoms.Invalid.Length.Memory.Corruption', qaid="947032")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3")
        fgt_a.execute('setvar -e "incidentserialno=(.*?) msg" -to SRNO')
        fgt_a.execute("fnsysctl ls -l  /var/log/log/FGT_A:VDOM1/pcap")
        fgt_a.execute(f'varexpect -v "{fgt_a.testbed.env.get_dynamic_var('SRNO')}" -for 947034 -t 5')
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display").expect('HTTP(.*?)block(.*?)countips=1', qaid="947032")
        fgt_a.execute("""
    config ips sensor
    edit  "cve"
    config entries
    edit 1
    set action reset
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("dia ips ssl clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 -S --delete-after http://PC_02:DESTINATION1/index.html")
        pc_01.execute("sleep 30")
        pc_01.execute("clear_buffer")
        pc_01.execute("curl -v http://PC_02:DESTINATION1/ips_data/1.mp4 -m 15")
        pc_01.execute("sleep 20").expect('Connection reset by peer', qaid="947032")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display").expect('action=\\"reset(.*?)service=\\"HTTP(.*?)dstport=80(.*)direction=\\"incoming(.*?)Adobe.Flash.MP4.Atoms.Invalid.Length.Memory.Corruption', qaid="947032")
        fgt_a.execute("""
    config ips sensor
    edit  "cve"
    config entries
    edit 1
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("dia ips ssl clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 -S --delete-after http://PC_02:DESTINATION1/index.html")
        pc_01.execute("sleep 30")
        pc_01.execute("clear_buffer")
        pc_01.execute("curl -v http://PC_02:DESTINATION1/ips_data/1.mp4 -O")
        pc_01.execute("sleep 20").expect('200 OK', qaid="947032")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display").expect('action=\\"detected(.*?)service=\\"HTTP(.*?)dstport=80(.*)direction=\\"incoming(.*?)Adobe.Flash.MP4.Atoms.Invalid.Length.Memory.Corruption', qaid="947032")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "cve"
    end
        """)
        fgt_a.execute("report 947032")
        fgt_a.execute("report 947034")

    # All assertions tracked under QAID 947032
    testbed.results.report("947032")
