"""
Auto-generated pytest test for QAID 821652

Original DSL: ../testcase/ips/topology1/821652.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__821652(testbed):
    """
    Verify Botnet signatures was move in IPS database from appctrl and send traffic to trigger
    
    QAID: 821652
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 50740
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    set nat enable
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 25 http://PC_02:DESTINATION1/index.html")
        pc_02.execute("sleep 30")
        pc_02.execute("clear_buffer")
        pc_02.execute("nc PC_05:IP_ETH1 80 < /root/BONET_test.TXT")
        pc_02.execute("sleep 10")
        pc_02.execute("ctrl_c")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('action=\\"dropped\\"(.*?)profile=\\"sensor-1\\"(.*?)backdoor: Vidar.Botnet', qaid="821652")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    set nat disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-1"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 821652")

    # All assertions tracked under QAID 821652
    testbed.results.report("821652")
