"""
Auto-generated pytest test for QAID 205814

Original DSL: ../testcase/ips/topology1/205814.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__205814(testbed):
    """
    IPS Regression Test Case 2.3
    
    QAID: 205814
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_02_03:Busy: create custom signatures")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "match small"
    set signature "F-SBID( --name \"match small\"; --attack_id 5835; --protocol tcp; --severity medium; --status disable; --default_action clear_session; --service http;  --pattern \"small\"; )"
    next
    end
        """)
        fgt_a.execute("show ips custom").expect('match small.*default_action clear_session', qaid="205814")
        fgt_a.execute("""
    config ips custom
    delete "match small"
    end
        """)
        fgt_a.execute("clear_buffer")
        fgt_a.execute("show ips custom").expect('match small', qaid="205814", should_fail=True)
        fgt_a.execute("""
    config ips custom
    purge
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 205814")

    # All assertions tracked under QAID 205814
    testbed.results.report("205814")
