"""
Auto-generated pytest test for QAID 741441

Original DSL: ../testcase/ips/topology1/741441.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__741441(testbed):
    """
    IPS Regression Test Case 17.1
    
    QAID: 741441
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_17_01:Busy: create custom signatures match_apache")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "test"
    set application DB2
    set comment ''
    set location server
    set os Windows
    set protocol IMAP
    set severity high
    set signature "F-SBID( --name \"test\"; --attack_id 6406; --severity low; --protocol tcp; --pattern \"ABCDEFG\";)"
    next
    end
        """)
        fgt_a.execute("sleep 5")
        fgt_a.execute("show ips custom test")
        fgt_a.execute("sleep 5").expect('signature(.*?)high(.*?)server(.*?)Windows(.*?)DB2(.*?)IMAP', qaid="741441")
        fgt_a.execute("""
    config ips custom
    del test
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 741441")

    # All assertions tracked under QAID 741441
    testbed.results.report("741441")
