"""
Auto-generated pytest test for QAID 206058

Original DSL: ../testcase/ips/topology1/206058.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__206058(testbed):
    """
    IPS Regression Test Case 24.3
    
    QAID: 206058
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_24.3:Busy: enable large_icmp signature with action pass")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    edit "111"
    set status enable
    set log enable
    set action block
    set quarantine attacker
    set quarantine-expiry 3m
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("dia user banned-ip clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping -s 45000 -c 5 PC_02:DESTINATION1")
        pc_02.execute("sleep 10").expect('5 received|5 packets received', qaid="206058", should_fail=True)
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?)ICMP.Oversized.Packet', qaid="206058")
        fgt_a.execute("sleep 10")
        fgt_a.execute("dia user banned-ip list").expect('PC_02:IP_ETH1', qaid="206058")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping -c 1 PC_02:DESTINATION1").expect('0 received|0 packets received', qaid="206058")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ping -c 3 PC_02:DESTINATION1")
        pc_01.execute("sleep 10").expect('64 bytes', qaid="206058")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia user banned-ip clear")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    delete "111"
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("report 206058")

    # All assertions tracked under QAID 206058
    testbed.results.report("206058")
