"""
Auto-generated pytest test for QAID topology1-tp

Original DSL: ../testcase/ips/topology1/topology1-tp.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_purge import helper_purge
from helpers.helper_downPort import helper_downPort
from helpers.helper_enable import helper_enable
from helpers.helper_setupA_tp import helper_setupA_tp
from helpers.helper_initializeA_tp import helper_initializeA_tp
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test_topology1_tp(testbed):
    """
    This is topology #1 TP mode for IPS regression test.
    
    QAID: topology1-tp
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Topology1:Busy:Resetting Firewall FGTA")
        if fgt_a.testbed.read_env_variables('FGT_A:VM') == 'yes':
            pass
        else:
            fgt_a.execute("resetFirewall")
        fgt_a.execute("comment Topology1:Busy:Cleanning up environment for FGTA")
        helper_purge(fgt_a)
        fgt_a.execute("comment set PORT6/7/8/9 down in Robot lab to avoid loop")
        fgt_a.execute("get sys status")
        fgt_a.execute('setvar -e "(?n)^Version: (.*?) v" -to PLATFORM_TYPE')
        if fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-3200D':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-3240C':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-3700D':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-3700DX':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-3800D':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiCarrier-3200D':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiCarrier-3240C':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiCarrier-3700D':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiCarrier-3700DX':
            helper_downPort(fgt_a)
        elif fgt_a.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiCarrier-3800D':
            helper_downPort(fgt_a)
        else:
            pass
        fgt_a.execute("comment Topology1:Busy:Creating vdoms for FGTA")
        helper_enable(fgt_a)
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Topology1:Busy:Setting up environment for FGTA")
        helper_setupA_tp(fgt_a)
        helper_initializeA_tp(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("show system settings")
        fgt_a.execute("sleep 2").expect('opmode transparent', qaid="topology1-tp")
        fgt_a.execute("report topology1-FGT_A_tp")

    # All assertions tracked under QAID topology1-tp
    testbed.results.report("topology1-tp")
