"""
Auto-generated pytest test for QAID 744714

Original DSL: ../testcase/ips/topology1/744714.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__744714(testbed):
    """
    IPS Regression Test Case 19.1
    
    QAID: 744714
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_19.1:Busy: enable large_icmp signature with action pass")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    edit 12705
    set status enable
    set rule 12705
    set action pass
    set log enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall interface-policy
    edit 1
    set interface FGT_A:PORT2
    set srcaddr "all"
    set dstaddr "all"
    set service "ALL"
    set ips-sensor-status enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("sleep 10")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping -c 3 PC_02:DESTINATION1 -R").expect('0 received|0 packets received', qaid="744714")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("sleep 10")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 10").expect('detected(.*?)IP.Record.Route.Option', qaid="744714")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_019.1:Busy: enable large_icmp signature with action block")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 12705
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping -c 3 PC_02:DESTINATION1 -R").expect('RR', qaid="744714", should_fail=True)
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("sleep 10")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?)IP.Record.Route.Option', qaid="744714")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall interface-policy
    delete 1
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    delete 12705
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("report 744714")

    # All assertions tracked under QAID 744714
    testbed.results.report("744714")
