"""
Auto-generated pytest test for QAID 983978

Original DSL: ../testcase/ips/topology1/983978.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__983978(testbed):
    """
    983978: Verify sctp-filter profile cofiguration with ppid filters
    
    QAID: 983978
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config sctp-filter profile
    edit "g-sctp"
    set comment ''
    config ppid-filters
    edit 1
    set ppid 1773535488
    set action reset
    set comment 'test ppid'
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("clear_buffer")
        fgt_a.execute("show full sctp-filter profile g-sctp").expect('ppid 1773535488(.*?)reset(.*?)test ppid', qaid="983978")
        fgt_a.execute("""
    config sctp-filter profile
    edit "g-sctp"
    config ppid-filters
    edit 1
    set action replace
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("clear_buffer")
        fgt_a.execute("show sctp-filter profile g-sctp").expect('ppid 1773535488(.*?)replace(.*?)test ppid', qaid="983978")
        fgt_a.execute("""
    config sctp-filter profile
    edit "g-sctp"
    config ppid-filters
    edit 1
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("clear_buffer")
        fgt_a.execute("show sctp-filter profile g-sctp").expect('ppid 1773535488(.*?)pass(.*?)test ppid', qaid="983978")
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config sctp-filter profile
    edit "sctp"
    set comment ''
    config ppid-filters
    edit 1
    set ppid 1773535488
    set action reset
    set comment 'test ppid'
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("clear_buffer")
        fgt_a.execute("show full sctp-filter profile sctp").expect('ppid 1773535488(.*?)reset(.*?)test ppid', qaid="983978")
        fgt_a.execute("""
    config sctp-filter profile
    edit "sctp"
    config ppid-filters
    edit 1
    set action replace
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("clear_buffer")
        fgt_a.execute("show sctp-filter profile sctp").expect('ppid 1773535488(.*?)replace(.*?)test ppid', qaid="983978")
        fgt_a.execute("""
    config sctp-filter profile
    edit "sctp"
    config ppid-filters
    edit 1
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("clear_buffer")
        fgt_a.execute("show sctp-filter profile sctp").expect('ppid 1773535488(.*?)pass(.*?)test ppid', qaid="983978")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 983978")

    # All assertions tracked under QAID 983978
    testbed.results.report("983978")
