"""
Auto-generated pytest test for QAID 821653

Original DSL: ../testcase/ips/topology1/821653.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__821653(testbed):
    """
    Verify industrial signature: app SCADA list in ips sensor and send traffic to trigger
    
    QAID: 821653
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set exclude-signatures none
    end
        """)
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set application SCADA
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("diag test app ipsm 15").expect('Self Test: Passed', qaid="821653")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 25 http://PC_01:DESTINATION1/index.html")
        pc_01.execute("sleep 30")
        pc_01.execute("clear_buffer")
        pc_01.execute("nc -4u PC_05:IP_ETH1 5512 < /root/31321.bin")
        pc_01.execute("sleep 25")
        pc_01.execute("ctrl_c")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('action=\\"dropped\\"(.*?)attackid=31321(.*?)profile=\\"sensor-1\\"(.*?)SCADA: ABB.Multiple.Products.RobNetScanHost.exe.Stack.Buffer.Overflow', qaid="821653")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-1"
    end
        """)
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    unset exclude-signatures
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 821653")
        fgt_a.execute("report 1146048")

    # All assertions tracked under QAID 821653
    testbed.results.report("821653")
