"""
Auto-generated pytest test for QAID topology1-wanopt-server

Original DSL: ../testcase/ips/topology1/topology1-wanopt-server.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_purge import helper_purge
from helpers.helper_enLongVD import helper_enLongVD
from helpers.helper_goroot import helper_goroot
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_goglobal import helper_goglobal


# ===== Test Function =====

def test_topology1_wanopt_server(testbed):
    """
    DUT: FGT_B WANOPT server FGT
    
    QAID: topology1-wanopt-server
    """
    with testbed.device('FGT_B') as fgt_b:
        if fgt_b.testbed.read_env_variables('FGT_A:VM') == 'yes':
            pass
        else:
            fgt_b.execute("resetFirewall")
        helper_purge(fgt_b)
        fgt_b.execute("diag deb reset")
        fgt_b.execute("""
    config system dns
    set primary FGT_B:DNS_PRIMARY
    set secondary FGT_B:DNS_SECONDARY
    set protocol cleartext
    end
        """)
        fgt_b.execute("diagnose test app dns 1")
        fgt_b.execute("diagnose test app dns 9")
        fgt_b.execute("""
    config system fortiguard
    set fortiguard-anycast disable
    set update-ffdb enable
    end
        """)
        fgt_b.execute("""
    config system global
    set hostname FGT_B_WanOpt
    set vdom-mode multi-vdom
    set admintimeout 480
    end
        """)
        helper_enLongVD(fgt_b)
        fgt_b.execute("""
    config vdom
    edit FGT_A:VDOM1
    end
        """)
        fgt_b.execute("sleep 5")
    with testbed.device('FGT_B') as fgt_b:
        helper_goroot(fgt_b)
        fgt_b.execute("""
    config firewall address
    purge
    end
        """)
        helper_outvdom(fgt_b)
        helper_govdom1(fgt_b)
        fgt_b.execute("""
    config firewall address
    purge
    end
        """)
        helper_outvdom(fgt_b)
    with testbed.device('FGT_B') as fgt_b:
        helper_goroot(fgt_b)
        if fgt_b.testbed.read_env_variables('FGT_A:VM') == 'yes':
            pass
        else:
            fgt_b.execute("""
    config router static
    purge
    end
            """)
        fgt_b.execute("""
    config firewall policy
    purge
    end
        """)
        fgt_b.execute("""
    config system dhcp server
    purge
    end
        """)
        helper_outvdom(fgt_b)
        helper_govdom1(fgt_b)
        if fgt_b.testbed.read_env_variables('FGT_B:LOG_DEVICE') == 'memory':
            fgt_b.execute("""
    config log memory filter
    set severity information
    end
            """)
        else:
            fgt_b.execute("""
    config log disk setting
    set status enable
    end
            """)
        fgt_b.execute("""
    config log memory setting
    set status enable
    end
        """)
        fgt_b.execute("""
    config log setting
    set local-out disable
    end
        """)
        fgt_b.execute("""
    config system interface
    edit "FGT_B:PORT1"
    set vdom FGT_B:VDOM1
    set mode static
    set ip FGT_B:IP_PORT1
    select allowaccess ping https ssh snmp http telnet fgfm
    set type physical
    next
    edit "FGT_B:PORT3"
    set vdom FGT_B:VDOM1
    set mode static
    set ip FGT_B:IP_PORT3
    select allowaccess ping https ssh snmp http telnet fgfm
    set type physical
    next
    end
        """)
        fgt_b.execute("""
    config router static
    edit 1
    set device "FGT_B:PORT1"
    set gateway FGT_B:GATEWAY
    next
    end
        """)
        helper_outvdom(fgt_b)
        helper_goglobal(fgt_b)
        fgt_b.execute("conf system global")
        fgt_b.execute("set management-vdom FGT_B:VDOM1")
        fgt_b.execute("set gui-ipv6 enable")
        fgt_b.execute("end")
        fgt_b.execute("dia de crashlog clear")
        helper_outvdom(fgt_b)
        helper_govdom1(fgt_b)
        fgt_b.execute("""
    config firewall ssl-ssh-profile
    edit "new-deep-inspection"
    config https
    set ports "443"
    end
        """)
        fgt_b.execute("""
    config ftps
    set ports "990"
    end
        """)
        fgt_b.execute("""
    config imaps
    set ports "993"
    end
        """)
        fgt_b.execute("""
    config pop3s
    set ports "995"
    end
        """)
        fgt_b.execute("""
    config smtps
    set ports "465"
    end
        """)
        fgt_b.execute("""
    config ssl-exempt
    purge
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        fgt_b.execute("""
    config wanopt settings
    set host-id "WanOpt_Svr"
    end
        """)
        fgt_b.execute("""
    config wanopt peer
    purge
    edit "WanOpt_Client"
    set ip FGT_B:IP_WanOpt_Client
    next
    end
        """)
        fgt_b.execute("""
    config firewall ssl-server
    edit "pc05"
    set ip PC_02:DESTINATION1
    set port 443
    set ssl-cert "Fortinet_SSL"
    next
    edit "pc05-8443"
    set ip PC_02:DESTINATION1
    set port 8443
    set ssl-cert "Fortinet_SSL"
    next
    end
        """)
        fgt_b.execute("""
    config firewall ssl-server
    edit "pc05"
    set ip PC_02:DESTINATION1
    set port 443
    set ssl-cert "Fortinet_CA_SSL"
    next
    edit "pc05-8443"
    set ip PC_02:DESTINATION1
    set port 8443
    set ssl-cert "Fortinet_CA_SSL"
    next
    end
        """)
        fgt_b.execute("""
    config firewall policy
    edit 1
    set srcintf "FGT_B:PORT3"
    set dstintf "FGT_B:PORT1"
    select srcaddr "all"
    select dstaddr "all"
    set action accept
    set schedule "always"
    select service "ALL"
    set nat enable
    set utm-status enable
    set inspection-mode proxy
    set wanopt enable
    set wanopt-detection passive
    next
    end
        """)
        fgt_b.execute("""
    config firewall proxy-policy
    edit 1
    set proxy wanopt
    set dstintf "FGT_B:PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set action accept
    set schedule "always"
    set service "ALL"
    next
    end
        """)
        fgt_b.execute("dia de crashlog clear")
        helper_outvdom(fgt_b)
    with testbed.device('FGT_B') as fgt_b:
        helper_goglobal(fgt_b)
        fgt_b.execute("dia hardware deviceinfo disk")
        fgt_b.execute("sleep 10")
        helper_outvdom(fgt_b)
        helper_govdom1(fgt_b)
        fgt_b.execute("""
    config log memory filter
    set severity information
    end
        """)
        fgt_b.execute("show firewall proxy-policy")
        fgt_b.execute("sleep 3").expect('set proxy wanopt', qaid="topology1-wanopt-server")
        fgt_b.execute("""
    config ips settings
    set proxy-inline-ips disable
    end
        """)
        helper_outvdom(fgt_b)
        helper_govdom1(fgt_b)
        fgt_b.execute("""
    config firewall policy
    edit 1
    set ips-sensor g-default
    set application-list g-default
    set av-profile g-default
    next
    end
        """)
        helper_outvdom(fgt_b)
        helper_goglobal(fgt_b)
        fgt_b.execute("""
    config ips global
    set database extended
    end
        """)
        fgt_b.execute("exe update-ips")
        fgt_b.execute("sleep 5")
        fgt_b.execute("exe update-now")
        fgt_b.execute("sleep 120")
        helper_outvdom(fgt_b)
        helper_govdom1(fgt_b)
        fgt_b.execute("""
    config firewall policy
    edit 1
    unset ips-sensor
    unset application-list
    unset av-profile
    next
    end
        """)
        helper_outvdom(fgt_b)
    with testbed.device('FGT_A') as fgt_a:
        if fgt_a.testbed.read_env_variables('FGT_A:VM') == 'yes':
            helper_govdom1(fgt_a)
            fgt_a.execute("""
    config router static
    purge
    edit 1
    set device "FGT_A:PORT3"
    set gateway FGT_A:GATEWAY_WANOPT
    next
    end
            """)
            helper_outvdom(fgt_a)
            helper_goglobal(fgt_a)
            fgt_a.execute("conf system global")
            fgt_a.execute("set management-vdom FGT_A:VDOM1")
            fgt_a.execute("end")
            helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set ips-sensor g-default
    set application-list g-default
    set av-profile g-default
    next
    end
        """)
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set database extended
    end
        """)
        fgt_a.execute("exe update-ips")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe update-now")
        fgt_a.execute("sleep 120")
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset ips-sensor
    unset application-list
    unset av-profile
    next
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report topology1-wanopt-server")

    # All assertions tracked under QAID topology1-wanopt-server
    testbed.results.report("topology1-wanopt-server")
