"""
Auto-generated pytest test for QAID ngfw-setup

Original DSL: ../testcase/ips/topology1/ngfw-setup.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test_ngfw_setup(testbed):
    """
    This script will change VDOM1 ngfw-mode from profile-based to policy-based. Firewall policy and firewall policy6 will be deleted. Instead prematch-policy and security-policy need to be configured to let traffic pass.
    
    QAID: ngfw-setup
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config system settings
    set ngfw-mode policy-based
    end
        """)
        fgt_a.execute("""
    config firewall central-snat-map
    edit 1
    set orig-addr "all"
    set srcintf "FGT_A:PORT2"
    set dst-addr "all"
    set dstintf "FGT_A:PORT1"
    next
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set name "prematch-1"
    set srcintf "FGT_A:PORT2"
    set dstintf "FGT_A:PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set srcaddr6 "all"
    set dstaddr6 "all"
    set service "ALL"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("""
    config firewall security-policy
    edit 2
    set name "allow-dns"
    set srcintf "FGT_A:PORT2"
    set dstintf "FGT_A:PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set srcaddr6 "all"
    set dstaddr6 "all"
    set enforce-default-app-port disable
    set service "DNS"
    set action accept
    set schedule "always"
    set logtraffic disable
    next
    edit 3
    set name "allow-app"
    set srcintf "FGT_A:PORT2"
    set dstintf "FGT_A:PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set srcaddr6 "all"
    set dstaddr6 "all"
    set action accept
    set schedule "always"
    set application 24533 16467
    set app-category 7 17 21
    next
    edit 4
    set name "allow-url"
    set srcintf "FGT_A:PORT2"
    set dstintf "FGT_A:PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set srcaddr6 "all"
    set dstaddr6 "all"
    set action accept
    set schedule "always"
    set url-category 37 35 36
    next
    edit 99
    set name "security-99"
    set srcintf "FGT_A:PORT2"
    set dstintf "FGT_A:PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set srcaddr6 "all"
    set dstaddr6 "all"
    set action accept
    set schedule "always"
    next
    end
        """)
        fgt_a.execute("show firewall security-policy")
        fgt_a.execute("sleep 2").expect('DNS', qaid="ngfw-setup")
        helper_outvdom(fgt_a)
        fgt_a.execute("report ngfw-setup")

    # All assertions tracked under QAID ngfw-setup
    testbed.results.report("ngfw-setup")
