"""
Auto-generated pytest test for QAID 946656

Original DSL: ../testcase/ips/topology1/946656.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__946656(testbed):
    """
    946656: Verify hold time value can be configured in vdom but not in GLOBAL
    
    QAID: 946656
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config sys ips
    set signature-hold-time 2d
    end
        """)
        fgt_a.execute("sleep 3")
        fgt_a.execute("show sys ips")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config sys ips
    show full
        """).expect('set signature-hold-time 0h', qaid="946656")
        fgt_a.expect('override-signature-hold-by-id', qaid="946656", should_fail=True)
        fgt_a.execute("set signature-hold-time 2d2h")
        fgt_a.execute("show full").expect('set signature-hold-time 2d2h', qaid="946656")
        fgt_a.expect('override-signature-hold-by-id enable', qaid="946656")
        fgt_a.execute("set override-signature-hold-by-id disable")
        fgt_a.execute("end")
        fgt_a.execute("show sys ips").expect('set signature-hold-time 2d2h', qaid="946656")
        fgt_a.expect('override-signature-hold-by-id disable', qaid="946656")
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config sys ips
    unset override-signature-hold-by-id
    unset signature-hold-time
    end
        """)
        fgt_a.execute("show sys ips").expect('override-signature-hold-by-id', qaid="946656", should_fail=True)
        fgt_a.expect('set signature-hold-time', qaid="946656", should_fail=True)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 946656")
        fgt_a.execute("report 946657")
        fgt_a.execute("report 946667")

    # All assertions tracked under QAID 946656
    testbed.results.report("946656")
