"""
Auto-generated pytest test for QAID 730347

Original DSL: ../testcase/ips/topology1/730347.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__730347(testbed):
    """
    Verify rate/threshold in firewall policy6 ips-sensor work
    
    QAID: 730347
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Configure IPS sensor and firewall policy6")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action block
    set rate-count 3
    set rate-duration 60
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 11
    set srcintf FGT_A:PORT2
    set dstintf FGT_A:PORT1
    set srcaddr6 "all"
    set dstaddr6 "all"
    set action accept
    set schedule "always"
    set service "ALL"
    set utm-status enable
    set ips-sensor "sensor-1"
    set profile-protocol-options "default"
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session6 clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping6 -c 4 2000:172:16:200::55")
        pc_02.execute("wget -t 1 -T 20 --delete-after http://[PC_05:IP6_ETH1]")
        pc_02.execute("sleep 60")
        pc_02.execute("cd PC_02:SCRIPT")
        pc_02.execute("./fork 10 3 wget -t 1 -T 20 --delete-after http://[PC_05:IP6_ETH1]/virus/eicar")
        pc_02.execute("sleep 30").expect('68/68', qaid="730347")
        pc_02.expect('68/68', qaid="730347")
        pc_02.expect('68/68', qaid="730347", should_fail=True)
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 10").expect('dropped(.*?)attackid=29844(.*?)Eicar.Virus.Test.File', qaid="730347")
        fgt_a.execute("""
    config firewall policy
    edit 11
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 730347")

    # All assertions tracked under QAID 730347
    testbed.results.report("730347")
