"""
Auto-generated pytest test for QAID 206005

Original DSL: ../testcase/ips/topology1/206005.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__206005(testbed):
    """
    IPS Regression Test Case 17.10
    
    QAID: 206005
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_17_10 Busy: create custom signatures match_small")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "match small"
    set signature "F-SBID( --name \"match small\"; --attack_id 5835; --protocol tcp; --severity medium; --status disable; --default_action clear_session; --service http;  --pattern \"small\"; )"
    next
    end
        """)
        fgt_a.execute("exe backup ipsuserdefsig ftp FGT_A:CUSTOMSIG1 PC_05:IP_ETH1 fosqa PC_05:PASSWORD").expect('OK', qaid="206005")
        helper_outvdom(fgt_a)
    with testbed.device('PC_05') as pc_05:
        pc_05.execute("more /home/fosqa/FGT_A:CUSTOMSIG1").expect('5835', qaid="206005")
        pc_05.execute("rm -f /home/fosqa/FGT_A:CUSTOMSIG1")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    delete "match small"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 206005")

    # All assertions tracked under QAID 206005
    testbed.results.report("206005")
