"""
Auto-generated pytest test for QAID 205961

Original DSL: ../testcase/ips/topology1/205961.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__205961(testbed):
    """
    Verify firewall can exclude hosts from IPS signature
    
    QAID: 205961
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 12880
    set status enable
    set rule 12880
    set action block
    set log enable
    config exempt-ip
    edit 1
    set dst-ip PC_05:IP_ETH1 255.255.255.255
    set src-ip PC_02:IP_ETH1 255.255.255.255
    next
    edit 2
    set dst-ip PC_02:IP_ETH1 255.255.255.255
    set src-ip PC_05:IP_ETH1 255.255.255.255
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping -c 10 PC_02:DESTINATION1")
        pc_02.execute("sleep 30")
        pc_02.execute("ping -s 45000 -c 10 PC_02:DESTINATION1")
        pc_02.execute("sleep 10").expect('45008 bytes', qaid="205961")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ping -s 45000 -c 3 PC_02:DESTINATION1")
        pc_01.execute("sleep 10").expect('0 received|0 packets received', qaid="205961")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?)ICMP.Oversized.Packet', qaid="205961")
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    edit 2
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    delete 12880
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("report 205961")

    # All assertions tracked under QAID 205961
    testbed.results.report("205961")
