"""
Auto-generated pytest test for QAID 801906

Original DSL: ../testcase/ips/topology1/801906.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__801906(testbed):
    """
    Verify quarantine expire time configuration work for ips-sensor and Dos-Policy via CLI
    
    QAID: 801906
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("comment Configure quarantine expire time for ips-sensor")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 12880
    set status enable
    set action block
    set quarantine attacker
    set quarantine-expiry 1d45m
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("show ips sensor sensor-1").expect('set quarantine-expiry 1d45m', qaid="801906")
        fgt_a.execute("comment Delete IPS sensor")
        fgt_a.execute("""
    config ips sensor
    delete "sensor-1"
    end
        """)
        fgt_a.execute("comment Configre qurantine expire time for DoS-policy")
        fgt_a.execute("""
    config firewall DoS-policy
    edit 1
    set interface "FGT_A:PORT2"
    set srcaddr "all"
    set dstaddr "all"
    set service "ALL"
    config anomaly
    edit "tcp_syn_flood"
    set status enable
    set log enable
    set action block
    set quarantine attacker
    set quarantine-expiry 7d12h50m
    set quarantine-log disable
    set threshold 100
    next
    edit "tcp_port_scan"
    set threshold 1000
    next
    edit "tcp_src_session"
    set threshold 5000
    next
    edit "tcp_dst_session"
    set threshold 5000
    next
    edit "udp_flood"
    set threshold 2000
    next
    edit "udp_scan"
    set threshold 2000
    next
    edit "udp_src_session"
    set threshold 5000
    next
    edit "udp_dst_session"
    set threshold 5000
    next
    edit "icmp_flood"
    set threshold 250
    next
    edit "icmp_sweep"
    set threshold 100
    next
    edit "icmp_src_session"
    set threshold 300
    next
    edit "icmp_dst_session"
    set threshold 1000
    next
    edit "ip_src_session"
    set threshold 100
    next
    edit "ip_dst_session"
    set threshold 5000
    next
    edit "sctp_flood"
    set threshold 2000
    next
    edit "sctp_scan"
    set threshold 1000
    next
    edit "sctp_src_session"
    set threshold 5000
    next
    edit "sctp_dst_session"
    set threshold 5000
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("show firewall DoS-policy 1").expect('set quarantine attacker', qaid="801906")
        fgt_a.expect('set quarantine-expiry 7d12h50m', qaid="801906")
        fgt_a.execute("comment Delete DoS-policy")
        fgt_a.execute("""
    config firewall DoS-policy
    delete 1
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 801906")

    # All assertions tracked under QAID 801906
    testbed.results.report("801906")
