"""
Auto-generated pytest test for QAID 848296

Original DSL: ../testcase/ips/topology1/848296.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__848296(testbed):
    """
    run.bat &ch file on Windows 7 to start SMB2 traffic
    
    QAID: 848296
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("get sys status")
        fgt_a.execute('setvar -e "(?n)^Version: (.*?) v" -to PLATFORM_TYPE')
        helper_outvdom(fgt_a)
    with testbed.device('PC_37') as pc_37:
        if pc_37.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-51E':
            pc_37.execute("smb-mount-copy-9.bat &")
            pc_37.execute("keep_running 1")
        elif pc_37.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-91E':
            pc_37.execute("smb-mount-copy-10.bat &")
            pc_37.execute("keep_running 1")
        elif pc_37.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-90D':
            pc_37.execute("smb-mount-copy-11.bat &")
            pc_37.execute("keep_running 1")
        elif pc_37.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-60E':
            pc_37.execute("smb-mount-copy-12.bat &")
            pc_37.execute("keep_running 1")
        elif pc_37.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-2000E':
            pc_37.execute("smb-mount-copy-13.bat &")
            pc_37.execute("keep_running 1")
        elif pc_37.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-500D':
            pc_37.execute("smb-mount-copy-14.bat &")
            pc_37.execute("keep_running 1")
        elif pc_37.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-501E':
            pc_37.execute("smb-mount-copy-15.bat &")
            pc_37.execute("keep_running 1")
        elif pc_37.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-3240C':
            pc_37.execute("smb-mount-copy-16.bat &")
            pc_37.execute("keep_running 1")
        else:
            pass
    with testbed.device('PC_40') as pc_40:
        if pc_40.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-51E':
            pc_40.execute("smb-mount-copy-9.bat &")
            pc_40.execute("keep_running 1")
        elif pc_40.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-91E':
            pc_40.execute("smb-mount-copy-10.bat &")
            pc_40.execute("keep_running 1")
        elif pc_40.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-90D':
            pc_40.execute("smb-mount-copy-11.bat &")
            pc_40.execute("keep_running 1")
        elif pc_40.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-60E':
            pc_40.execute("smb-mount-copy-12.bat &")
            pc_40.execute("keep_running 1")
        elif pc_40.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-2000E':
            pc_40.execute("smb-mount-copy-13.bat &")
            pc_40.execute("keep_running 1")
        elif pc_40.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-500D':
            pc_40.execute("smb-mount-copy-14.bat &")
            pc_40.execute("keep_running 1")
        elif pc_40.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-501E':
            pc_40.execute("smb-mount-copy-15.bat &")
            pc_40.execute("keep_running 1")
        elif pc_40.testbed.env.get_dynamic_var('PLATFORM_TYPE') == 'FortiGate-3240C':
            pc_40.execute("smb-mount-copy-16.bat &")
            pc_40.execute("keep_running 1")
        else:
            pass
        pc_40.execute("sleep 3500")
    with testbed.device('PC_37') as pc_37:
        pc_37.execute("keep_running 0")
    with testbed.device('PC_40') as pc_40:
        pc_40.execute("keep_running 0")
        pc_40.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session filter dport 445")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log filter field service SMB")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('service=\\"SMB', qaid="848296")
        fgt_a.execute("diag debug crashlog read | grep cons").expect('conserve mode', qaid="848296", should_fail=True)
        fgt_a.execute("diag debug crashlog read | grep cons").expect('conserve mode', qaid="848296", should_fail=True)
        fgt_a.execute("diag debug crashlog read | grep firmware -A 100").expect('application', qaid="848296", should_fail=True)
        fgt_a.execute("diag debug crashlog read | grep cons -A 10").expect('conserve mode', qaid="848296", should_fail=True)
        fgt_a.execute("diag debug crashlog read | grep firmware -A 100").expect('application', qaid="848296", should_fail=True)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 848296")
        fgt_a.execute("report 838381")
        fgt_a.execute("report 838382")
        fgt_a.execute("report 840407")

    # All assertions tracked under QAID 848296
    testbed.results.report("848296")
