"""
Auto-generated pytest test for QAID updateSSH-nat

Original DSL: ../testcase/ips/topology1/updateSSH-nat.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed


# ===== Test Function =====

def test_updateSSH_nat(testbed):
    """
    ################## PC_01 ###################
    
    QAID: updateSSH-nat
    """
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment ################### PC_01 ###################")
        pc_01.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_A:IP_VLAN100')
        pc_01.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_A:EXT_IP')
        pc_01.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_C:IP1')
        pc_01.execute("sleep 3")
        pc_01.execute("ssh sshadmin@FGT_A:EXT_IP -o StrictHostKeyChecking=no")
        pc_01.execute("sleep 5")
        pc_01.execute("exit")
        pc_01.execute("sleep 10")
        pc_01.execute("ssh sshadmin@FGT_C:IP1 -o StrictHostKeyChecking=no")
        pc_01.execute("sleep 5")
        pc_01.execute("exit")
        pc_01.execute("sleep 10")
        pc_01.execute("ping -c 10 PC_02:DESTINATION1")
        pc_01.execute("sleep 20").expect('64 bytes', qaid="updateSSH-nat")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("comment ################### PC_02 ###################")
        pc_02.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_A:INT_IP')
        pc_02.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_A:SECIP_PORT2')
        pc_02.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_A:EXT_IP')
        pc_02.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_C:IP1')
        pc_02.execute("sleep 3")
        pc_02.execute("ssh sshadmin@FGT_A:INT_IP -o StrictHostKeyChecking=no")
        pc_02.execute("sleep 5")
        pc_02.execute("exit")
        pc_02.execute("sleep 10")
        pc_02.execute("ssh sshadmin@FGT_A:SECIP_PORT2 -o StrictHostKeyChecking=no")
        pc_02.execute("sleep 5")
        pc_02.execute("exit")
        pc_02.execute("sleep 10")
        pc_02.execute("ssh sshadmin@FGT_A:EXT_IP -o StrictHostKeyChecking=no")
        pc_02.execute("sleep 5")
        pc_02.execute("exit")
        pc_02.execute("sleep 10")
        pc_02.execute("ssh sshadmin@FGT_C:IP1  -o StrictHostKeyChecking=no")
        pc_02.execute("sleep 5")
        pc_02.execute("exit")
        pc_02.execute("sleep 10")
        pc_02.execute("ping -c 10 PC_02:DESTINATION1")
        pc_02.execute("sleep 20").expect('64 bytes', qaid="updateSSH-nat")
        pc_02.execute("report updateSSH-nat")

    # All assertions tracked under QAID updateSSH-nat
    testbed.results.report("updateSSH-nat")
