"""
Auto-generated pytest test for QAID 755617

Original DSL: ../testcase/ips/topology1/755617.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__755617(testbed):
    """
    Verify SERVER: ips sensor can detect SSL traffic(https) signature when it's in wanopt tunnel
    
    QAID: 755617
    """
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("comment Create ips sensor to block eicar and add this sensor to firewall proxy-policy")
        helper_govdom1(fgt_b)
        fgt_b.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action block
    next
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        fgt_b.execute("""
    config firewall proxy-policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    set ssl-ssh-profile "new-deep-inspection"
    set profile-protocol-options "default"
    next
    end
        """)
        fgt_b.execute("diag ips session clear")
        fgt_b.execute("diag sys session clear")
        fgt_b.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_b.execute("exe log filter category 4")
        fgt_b.execute("exe log delete-all")
        fgt_b.execute("sleep 25")
        fgt_b.execute("comment Clear wad statistics")
        fgt_b.execute("sleep 5")
        helper_outvdom(fgt_b)
        fgt_b.execute("comment Download eicar via http")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 5 https://PC_02:DESTINATION1/virus/eicar --no-check-certificate")
        pc_01.execute("sleep 15").expect('Giving up|503 ERROR|ERROR 403: Forbidden', qaid="755617")
    with testbed.device('FGT_B') as fgt_b:
        helper_govdom1(fgt_b)
        fgt_b.execute("comment Check IPS and traffic log")
        fgt_b.execute("dia sys session clear")
        fgt_b.execute("sleep 5")
        fgt_b.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_b.execute("exe log filter category 4")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 5").expect('dropped(.*?)Eicar.Virus.Test.File', qaid="755617")
        fgt_b.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_b.execute("exe log filter category 0")
        fgt_b.execute("exe log display")
        fgt_b.execute("sleep 5").expect('dstport=443(.*?)utmaction=\\"block(.*?)countips=1', qaid="755617")
        fgt_b.execute("comment Clean up environment")
        fgt_b.execute("""
    config firewall proxy-policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_b.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_b.execute("next")
        fgt_b.execute("end")
        helper_outvdom(fgt_b)
        fgt_b.execute("report 755617")

    # All assertions tracked under QAID 755617
    testbed.results.report("755617")
