"""
Auto-generated pytest test for QAID 895492

Original DSL: ../testcase/ips/topology1/895492.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__895492(testbed):
    """
    NGFW: verify that filter in IPS sensor works well
    
    QAID: 895492
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "ips-ngfw"
    config entries
    edit 1
    set severity critical
    set status enable
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall security-policy
    edit 99
    set utm-status enable
    set app-category 12 15
    set ips-sensor "ips-ngfw"
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 20 https://PC_02:DESTINATION1 --no-check-certificate")
        pc_02.execute("sleep 22")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 15 http://PC_02:DESTINATION1/ips_data/1.mp4 --no-check-certificate")
        pc_02.execute("sleep 20").expect('100%', qaid="895492")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('detected(.*?)service=\\"HTTP(.*?)dstport=80(.*?)direction=\\"incoming\\"(.*?)ips-ngfw(.*?)Adobe.Flash.MP4.Atoms.Invalid.Length.Memory.Corruption', qaid="895492")
        fgt_a.execute("""
    config firewall security-policy
    edit 99
    unset ips-sensor
    unset app-category
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "ips-ngfw"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 895492")

    # All assertions tracked under QAID 895492
    testbed.results.report("895492")
