ORIOLE_REPORT_FOLDER = "."
SUMMARY_FILE_NAME_PREFIX = "AutoTesting_Oriole_"
FILE_EXT = ".json"


ORIOLE_SUBMIT_URL = r"http://172.16.100.117/wsqadb/AutoTestResult?wsdl"
TEMPLATE_FILE_NAME = "summary.template"

ORIOLE_REPORT_FIXED_FIELDS = {
    "cidb": "1.00111",
    "avdb": "1.00000",
    "dbdb": "0.00000",
    "nids": "6.00741",
    "mmdb": "0.00000",
    "isdb": "6.00741",
    "flen": "7.00006",
    "total": "1",
    "aven": "6.00151",
    "apdb": "6.00741",
    "nids_ext": "6.00741",
    "ffdb": "0.00000",
    "mudb": "1.00001",
    "bios": "05000006",
    "ipge": "3.00041",
    "SN": "FG39E6T018900077",
    "crdb": "1.00021",
    "mcdb": "0.00000",
}

HOST = "172.18.52.254"
PORT = "8090"

ORIOLE_FIELD_FOS_SOURCE = {
    "apdb": ["Application Definitions"],
    "avdb": ["Virus Definitions"],
    "avdef": ["Virus Definitions", "Extended set", "Flow-based Virus Definitions"],
    "aven": ["AV Engine"],
    "bios": ["BIOS version"],
    "build": ["build"],
    "eavdf": ["Extended set"],
    "favdf": ["Flow-based Virus Definitions"],
    "flen": ["IPS Attack Engine"],
    "ipsdef": ["Attack Definitions", "Attack Extended Definitions"],
    "nids": ["Attack Definitions"],
    "nids_ext": ["Attack Extended Definitions"],
    "platform": ["platform"],
    "SN": ["Serial-Number"],
    "snmp_mib": ["build"],
}

ORIOLE_FIELD_MAPPING = {
    "AS DB Version": "asever",
    "AS Engine": "aseeng",
    "AV DB Version": "avdef",
    "AV Engine": "aven",
    "Application Definitions": "apdb",
    "BIOS": "bios",
    "Botnet DB": "ibdb",
    "Botnet DB Version": "botnetdef",
    "Botnet Definition": "ibdb",
    "Botnet Domain Database": "dbdb",
    "Browser-Chrome": "browser_gcr",
    "Browser-FF": "browser_ff",
    "Browser-IE": "browser_ie",
    "Browser-Safari": "browser_saf",
    "Build": "build",
    "Certificate Bundle": "crdb",
    "DUT serial number": "SN",
    "Device OS DB": "cidb",
    "EMS": "ems",
    "FAP": "fap",
    "FDN": "fdn",
    "FEXP": "fexp",
    "FEXP-Android": "fexp_droid",
    "FEXP-iOS": "fexp_ios",
    "FOS": "fos",
    "FSSO": "fsso",
    "FortiAP": "fap",
    "FortiAnalyzer": "faz",
    "FortiAuthenticator": "fac",
    "FortiClient-Android": "fct_droid",
    "FortiClient-ChromeOS": "fct_chrome",
    "FortiClient-Mac": "fct_mac",
    "FortiClient-Win": "fct",
    "FortiClient-iOS": "fct_ios",
    "FortiCloud": "fcld",
    "FortiExtender": "fext",
    "FortiManager": "fmg",
    "FortiOS": "fos",
    "FortiSASE Controller": "sase_controller",
    "FortiSASE SIA UI": "fsase_sia_ui",
    "FortiSandbox": "fsa",
    "FortiSwitch": "fsw",
    "FortiSwitchATCA": "ft",
    "FortiSwitchOS": "fsw",
    "IP Geography DB": "ipge",
    "IPS DB Version": "nids",
    "IPS Engine": "flen",
    "IPS Extended DB Version": "nids_ext",
    "IPS Malicious URL Database": "mudb",
    "Industrial Attack Definitions": "isdb",
    "Internet-service Database Apps": "ffdb",
    "Malicious Certificate Database": "mcdb",
    "Mobile Malware Definitions": "mmdb",
    "Platform": "platform_id",
    "Platform Generation": "pltgen",
    "SDNConnector": "sdnconn",
    "SDNS": "sdns",
    "SNMP-MIB": "snmp_mib",
    "SSL-VPN": "sslvpn",
    "Security Rating DB": "sfas",
    "URL White list": "uwdb",
    "VCM DB Version": "vcmver",
    "VCM Engine": "vcmeng",
    "VCM Plugin": "vcm_plugin",
    "VM DB Version": "vmver",
    "VM Engine": "vmeng",
}
