"""
Auto-generated pytest test for QAID 744749

Original DSL: ../testcase/ips/topology1/744749.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__744749(testbed):
    """
    Verify interface-policy work for ipv6 traffic to ips-sensor/application-control
    
    QAID: 744749
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Config IPS sensor and AppCtrl list in firewall interface policy6")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config application list
    edit "app-list-1"
    config entries
    edit 1
    set category 5
    next
    edit 2
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall interface-policy6
    edit 1
    set interface "FGT_A:PORT2"
    set srcaddr6 "all"
    set dstaddr6 "all"
    set service6 "ALL"
    set ips-sensor-status enable
    set ips-sensor "sensor-1"
    set application-list-status enable
    set application-list "app-list-1"
    next
    end
        """)
        fgt_a.execute("diag sys session6 clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 --delete-after http://[PC_05:IP6_ETH1]")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 15 --delete-after http://[PC_05:IP6_ETH1]/virus/eicar")
        pc_02.execute("sleep 20").expect('Connection timed out', qaid="744749")
        pc_02.execute("curl -v -6 -g -m 10 http://[PC_05:IP6_ETH1]/app_data/story.mp3")
        pc_02.execute("sleep 5").expect('Application Blocked', qaid="744749")
    with testbed.device('PC_02_2') as pc_02_2:
        pc_02_2.execute("pkill curl")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('dropped(.*?)Eicar.Virus.Test.File', qaid="744749")
        fgt_a.execute("exe log filter category 10")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('app-list-1(.*?)block(.*?)HTTP.Audio', qaid="744749")
        fgt_a.execute("comment Clear environment")
        fgt_a.execute("""
    config firewall interface-policy6
    delete 1
    end
        """)
        fgt_a.execute("""
    config ips sensor
    delete "sensor-1"
    end
        """)
        fgt_a.execute("""
    config application list
    delete "app-list-1"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 744749")

    # All assertions tracked under QAID 744749
    testbed.results.report("744749")
