"""
Auto-generated pytest test for QAID 946668

Original DSL: ../testcase/ips/topology1/946668.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__946668(testbed):
    """
    946668: Verify enable override option will allow the signatures specified by IDs to be triggered even if they are on hold
    
    QAID: 946668
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config system ntp
    set ntpsync disable
    end
        """)
        fgt_a.execute("""
    config system global
    set timezone Europe\/London
    end
        """)
        fgt_a.execute("execute date 2022-09-09")
        fgt_a.execute("sleep 30")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config sys ips
    set signature-hold-time 2d
    set override-signature-hold-by-id enable
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    set ssl-ssh-profile "new-deep-inspection"
    set nat enable
    set nat enable
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("dia ips ssl clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        fgt_a.execute("dia ips signature on-hold vd1 29844").expect('Rule: 29844(.*?)last updated', qaid="946668")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 -S --delete-after http://PC_02:DESTINATION1/index.html")
        pc_01.execute("sleep 30")
        pc_01.execute("clear_buffer")
        pc_01.execute("wget -t 1 -T 20  http://PC_05:IP_ETH1/virus/eicar")
        pc_01.execute("sleep 20").expect('Connection timed out', qaid="946668")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display").expect('signature(.*?)dropped(.*?)Eicar.Virus.Test.File', qaid="946668")
        fgt_a.expect('(signature is on hold)', qaid="946668", should_fail=True)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-1"
    end
        """)
        fgt_a.execute("""
    config sys ips
    unset override-signature-hold-by-id
    unset signature-hold-time
    end
        """)
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config system ntp
    set ntpsync enable
    set syncinterval 30
    end
        """)
        fgt_a.execute("""
    config system global
    set timezone Canada\/Pacific
    end
        """)
        fgt_a.execute("sleep 30")
        fgt_a.execute("report 946668")

    # All assertions tracked under QAID 946668
    testbed.results.report("946668")
