"""
Auto-generated pytest test for QAID 729753

Original DSL: ../testcase/ips/topology1/729753.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_goglobal import helper_goglobal


# ===== Test Function =====

def test__729753(testbed):
    """
    Verify CLIENT: ips can detected/block/reset predefined signature for http/ftp traffic
    
    QAID: 729753
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Create ips sensor to detect eicar and add this sensor to firewall policy")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set srcintf "PORT2"
    set dstintf "PORT3"
    set srcaddr "all"
    set dstaddr "all"
    set action accept
    set schedule "always"
    set service "ALL"
    set utm-status enable
    set ips-sensor "sensor-1"
    set profile-protocol-options "default"
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 25")
        helper_outvdom(fgt_a)
        fgt_a.execute("comment Clear wad statistics")
        helper_goglobal(fgt_a)
        fgt_a.execute("sleep 5")
        helper_outvdom(fgt_a)
        fgt_a.execute("comment Download eicar via http")
    with testbed.device('PC_05') as pc_05:
        pc_05.execute("cp /var/www/virus/eicar /home/fosqa/eicar")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 5 http://PC_02:DESTINATION1/virus/eicar")
        pc_01.execute("sleep 15").expect('100%', qaid="729753")
        pc_01.execute("comment Check IPS log and then change action on signature to block")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('detected(.*?)Eicar.Virus.Test.File', qaid="729753")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('service=\\"HTTP(.*?)utmaction=\\"allow(.*?)countips', qaid="729753")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 3")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment Download eicar via http")
        pc_01.execute("wget -t 1 -T 5 http://PC_02:DESTINATION1/virus/eicar")
        pc_01.execute("sleep 15").expect('Giving up', qaid="729753")
        pc_01.execute("comment Check IPS log and then change action on signature to reset")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('dropped(.*?)Eicar.Virus.Test.File', qaid="729753")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('service=\\"HTTP(.*?)utmaction=\\"block(.*?)countips=1', qaid="729753")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 3")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action reset
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment Download eicar via ftp")
        pc_01.execute('wget -t 1 -T 5 ftp://fosqa:"PC_02:PASSWORD"@PC_02:DESTINATION1/eicar')
        pc_01.execute("sleep 15").expect('Data transfer aborted', qaid="729753")
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Check IPS log")
        helper_govdom1(fgt_a)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('reset(.*?)Eicar.Virus.Test.File', qaid="729753")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('dstport=21(.*?)service=\\"FTP(.*?)action=\\"accept', qaid="729753")
        fgt_a.execute("comment Check that traffic goes through tunnel")
        fgt_a.execute('diagnose wad stats worker.protos show | grep "http.tunnel"')
        fgt_a.execute("sleep 5").expect('tunnel.bytes_in.*?([1-9][0-9]*).*?tunnel.bytes_out.*?([1-9][0-9]*)', qaid="729753")
        fgt_a.execute('diagnose wad stats worker.protos show | grep "protos.ftp"')
        fgt_a.execute("sleep 5").expect('tunnel.bytes_in.*?([1-9][0-9]*).*?tunnel.bytes_out.*?([1-9][0-9]*)', qaid="729753")
        fgt_a.execute("comment Clean up environment")
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset ips-sensor
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        helper_outvdom(fgt_a)
    with testbed.device('PC_05') as pc_05:
        pc_05.execute("rm /home/fosqa/eicar")
        pc_05.execute("report 729753")
        pc_05.execute("report 746987")

    # All assertions tracked under QAID 729753
    testbed.results.report("729753")
