"""
Auto-generated pytest test for QAID topology1-wanopt-client

Original DSL: ../testcase/ips/topology1/topology1-wanopt-client.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_purge import helper_purge
from helpers.helper_goroot import helper_goroot
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_goglobal import helper_goglobal


# ===== Test Function =====

def test_topology1_wanopt_client(testbed):
    """
    DUT: FGT_A WANOPT mode
    
    QAID: topology1-wanopt-client
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("resetFirewall")
        if fgt_a.testbed.read_env_variables('FGT_A:VM') == 'yes':
            fgt_a.execute("""
    config system fortiguard
    set update-server-location any
    end
            """)
            fgt_a.execute("""
    config system dns
    set primary FGT_A:DNS_PRIMARY
    set secondary FGT_A:DNS_SECONDARY
    set protocol cleartext
    end
            """)
            fgt_a.execute("""
    config system interface
    edit "port9"
    set vdom "root"
    set ip 10.6.30.190 255.255.255.0
    set allowaccess ping https ssh http telnet fgfm
    next
    end
            """)
            fgt_a.execute("""
    config router static
    edit 1
    set gateway 10.6.30.254
    set device "port9"
    next
    end
            """)
        helper_purge(fgt_a)
        fgt_a.execute("""
    config system dns
    set primary FGT_A:DNS_PRIMARY
    set secondary FGT_A:DNS_SECONDARY
    set protocol cleartext
    end
        """)
        fgt_a.execute("""
    config system fortiguard
    set fortiguard-anycast disable
    end
        """)
        fgt_a.execute("""
    config system console
    set output standard
    end
        """)
        fgt_a.execute("diagnose test app dns 1")
        fgt_a.execute("diagnose test app dns 9")
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("""
    config system global
    set hostname FGT_A_WanOpt
    set vdom-mode multi-vdom
    set admintimeout 480
    end
        """)
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("""
    config vdom
    edit FGT_A:VDOM1
    end
        """)
        fgt_a.execute("sleep 5")
    with testbed.device('FGT_A') as fgt_a:
        helper_goroot(fgt_a)
        fgt_a.execute("""
    config firewall address
    purge
    end
        """)
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall address
    purge
    end
        """)
        helper_outvdom(fgt_a)
    with testbed.device('FGT_A') as fgt_a:
        helper_goroot(fgt_a)
        fgt_a.execute("""
    config firewall policy
    purge
    end
        """)
        fgt_a.execute("""
    config system dhcp server
    purge
    end
        """)
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        if fgt_a.testbed.read_env_variables('FGT_A:VM') == 'yes':
            pass
        else:
            fgt_a.execute("conf system global")
            fgt_a.execute("set management-vdom FGT_A:VDOM1")
            fgt_a.execute("end")
        fgt_a.execute("conf system global")
        fgt_a.execute("set gui-ipv6 enable")
        fgt_a.execute("end")
        fgt_a.execute("""
    config system interface
    edit "FGT_A:PORT2"
    set vdom FGT_A:VDOM1
    set mode static
    set ip FGT_A:IP_PORT2
    select allowaccess ping https ssh snmp http telnet fgfm
    set type physical
    next
    edit "FGT_A:PORT3"
    set vdom FGT_A:VDOM1
    set mode static
    set ip FGT_A:IP_PORT3
    select allowaccess ping https ssh snmp http telnet fgfm
    set type physical
    next
    end
        """)
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        if fgt_a.testbed.read_env_variables('FGT_A:LOG_DEVICE') == 'memory':
            fgt_a.execute("""
    config log memory filter
    set severity information
    end
            """)
        else:
            fgt_a.execute("""
    config log disk setting
    set status enable
    end
            """)
        fgt_a.execute("""
    config log memory setting
    set status enable
    end
        """)
        fgt_a.execute("""
    config log setting
    set local-out disable
    end
        """)
        if fgt_a.testbed.read_env_variables('FGT_A:VM') == 'yes':
            pass
        else:
            fgt_a.execute("""
    config router static
    edit 1
    set device "FGT_A:PORT3"
    set gateway FGT_A:GATEWAY_WANOPT
    next
    end
            """)
        fgt_a.execute("""
    config firewall ssl-ssh-profile
    edit "new-deep-inspection"
    config https
    set ports "443"
    end
        """)
        fgt_a.execute("""
    config ftps
    set ports "990"
    end
        """)
        fgt_a.execute("""
    config imaps
    set ports "993"
    end
        """)
        fgt_a.execute("""
    config pop3s
    set ports "995"
    end
        """)
        fgt_a.execute("""
    config smtps
    set ports "465"
    end
        """)
        fgt_a.execute("""
    config ssl-exempt
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set srcintf "FGT_A:PORT2"
    set dstintf "FGT_A:PORT3"
    select srcaddr "all"
    select dstaddr "all"
    set action accept
    set schedule "always"
    select service "ALL"
    set utm-status enable
    set nat enable
    set profile-protocol-options "default"
    set ssl-ssh-profile new-deep-inspection
    next
    end
        """)
        fgt_a.execute("""
    config wanopt settings
    set host-id "WanOpt_Client"
    end
        """)
        fgt_a.execute("""
    config wanopt peer
    purge
    edit "WanOpt_Svr"
    set ip FGT_A:IP_WanOpt_Svr
    next
    end
        """)
        fgt_a.execute("""
    config wanopt profile
    edit "wan-all"
    set transparent disable
    set comments "Profile for all protocols"
    config http
    set status enable
    set ssl enable
    end
        """)
        fgt_a.execute("""
    config cifs
    set status enable
    end
        """)
        fgt_a.execute("""
    config ftp
    set status enable
    end
        """)
        fgt_a.execute("""
    config tcp
    set status enable
    set port 25-8995
    set ssl enable
    set ssl-port 465 993 995
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute('edit "wan-http"')
        fgt_a.execute("set transparent disable")
        fgt_a.execute("""
    config http
    set status enable
    set ssl enable
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute('edit "wan-tcp"')
        fgt_a.execute("set transparent disable")
        fgt_a.execute("""
    config tcp
    set status enable
    set port 25-8995
    set ssl enable
    set ssl-port 465 993 995
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall profile-protocol-options
    edit "nonstandard port"
    config http
    set ports 80 8080
    unset options
    unset post-lang
    end
        """)
        fgt_a.execute("""
    config ftp
    set ports 21
    unset options
    end
        """)
        fgt_a.execute("""
    config imap
    set ports 143
    set options fragmail
    end
        """)
        fgt_a.execute("""
    config mapi
    set ports 135
    set options fragmail
    end
        """)
        fgt_a.execute("""
    config pop3
    set ports 110
    set options fragmail
    end
        """)
        fgt_a.execute("""
    config smtp
    set ports 25
    set options fragmail
    end
        """)
        fgt_a.execute("""
    config nntp
    set ports 119
    unset options
    end
        """)
        fgt_a.execute("""
    config dns
    set ports 53
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall ssl-ssh-profile
    edit "new-deep-inspection"
    config https
    set ports 443 8443
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set inspection-mode proxy
    set wanopt enable
    set wanopt-detection active
    set wanopt-profile wan-all
    next
    end
        """)
        fgt_a.execute("""
    config ips settings
    set proxy-inline-ips disable
    end
        """)
        helper_outvdom(fgt_a)
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("show firewall policy")
        fgt_a.execute("sleep 3").expect('wan-all', qaid="topology1-wanopt-client")
        fgt_a.execute("show wanopt profile wan-all")
        fgt_a.execute("sleep 3").expect('config http', qaid="topology1-wanopt-client")
        fgt_a.execute("report topology1-wanopt-client")

    # All assertions tracked under QAID topology1-wanopt-client
    testbed.results.report("topology1-wanopt-client")
