"""
Auto-generated pytest test for QAID 826626

Original DSL: ../testcase/ips/topology1/826626.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__826626(testbed):
    """
    Verify by default "sync-session-ttl" enable in "config ips global"
    
    QAID: 826626
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set sync-session-ttl enable
    set engine-count 1
    end
        """)
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config system session-ttl
    set default 600
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set status enable
    set action pass
    set log enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("telnet PC_02:DESTINATION1").expect('login:', qaid="826626")
        pc_02.execute("root").expect('Password:', qaid="826626")
        pc_02.execute("PC_05:PASSWORD").expect('#', qaid="826626")
        pc_02.execute("keep_running 1")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips filter set 'port 23'")
        fgt_a.execute("dia ips session list")
        fgt_a.execute('setvar -e "idle:(.*?) flag" -to i')
        fgt_a.execute('setvar -e "(?n)expire: (.*?)\r" -to e')
        fgt_a.execute("<intchange 600 - i>")
        fgt_a.execute("compare -v1 i -v2 e -for 826626")
        fgt_a.execute("dia sys session filter src PC_02:IP_ETH1")
        fgt_a.execute("dia sys session filter dst PC_02:DESTINATION1")
        fgt_a.execute("dia sys session filter dport 23")
        fgt_a.execute("dia sys session list")
        fgt_a.execute("sleep 3").expect('timeout=600', qaid="826626")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("exit")
        pc_02.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config system session-ttl
    unset default
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-1"
    end
        """)
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set engine-count 0
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 826626")

    # All assertions tracked under QAID 826626
    testbed.results.report("826626")
