"""
Auto-generated pytest test for QAID setupPC-tp

Original DSL: ../testcase/ips/topology1/setupPC-tp.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed


# ===== Test Function =====

def test_setupPC_tp(testbed):
    """
    Update PC_01/PC_02 IP address for TP setup
    
    QAID: setupPC-tp
    """
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ip addr flush dev PC_01:ETH1")
        pc_01.execute("ip route flush dev PC_01:ETH1")
        pc_01.execute("ip -6 addr flush dev PC_01:ETH1")
        pc_01.execute("ip -6 route flush dev PC_01:ETH1")
        pc_01.execute("ip addr flush dev PC_01:ETH2")
        pc_01.execute("ip route flush dev PC_01:ETH2")
        pc_01.execute("ip addr flush dev PC_01:VLAN100")
        pc_01.execute("ip route flush dev PC_01:VLAN100")
        pc_01.execute("ifconfig PC_01:ETH1 PC_01:IP_ETH1_TP netmask 255.255.255.0 broadcast 172.16.200.255")
        pc_01.execute("route add default gw FGT_A:GATEWAY_VD1")
        pc_01.execute("sleep 5")
        pc_01.execute("ifconfig PC_01:ETH1 inet6 add PC_01:IP6_ETH1_TP/64")
        pc_01.execute("ifconfig")
        pc_01.execute("sleep 3")
        pc_01.execute("expect -e PC_01:IP6_ETH1_TP -for setupPC-tp -t 5")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ip addr flush dev PC_02:ETH1")
        pc_02.execute("ip route flush dev PC_02:ETH1")
        pc_02.execute("ip -6 addr flush dev PC_02:ETH1")
        pc_02.execute("ip -6 route flush dev PC_02:ETH1")
        pc_02.execute("ifconfig PC_02:ETH1 PC_02:IP_ETH1_TP netmask 255.255.255.0 broadcast 172.16.200.255")
        pc_02.execute("route add default gw FGT_A:GATEWAY_VD1")
        pc_02.execute("sleep 5")
        pc_02.execute("ifconfig PC_02:ETH1 inet6 add PC_02:IP6_ETH1_TP/64")
        pc_02.execute("ifconfig")
        pc_02.execute("sleep 3")
        pc_02.execute("expect -e PC_02:IP6_ETH1_TP -for setupPC-tp -t 5")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_A:EXT_IP')
        pc_01.execute('ssh-keygen -f "/root/.ssh/known_hosts" -R FGT_C:IP1')
        pc_01.execute("sleep 3")
        pc_01.execute("ssh sshadmin@FGT_A:EXT_IP -o StrictHostKeyChecking=no")
        pc_01.execute("sleep 15")
        pc_01.execute("exit")
        pc_01.execute("sleep 10")
        pc_01.execute("ssh sshadmin@FGT_C:IP1 -o StrictHostKeyChecking=no")
        pc_01.execute("sleep 5")
        pc_01.execute("exit")
        pc_01.execute("sleep 10")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("comment Verify if networking between PC01 and PC05 is ok")
        pc_01.execute("ping -c 10 PC_01:DESTINATION1")
        pc_01.execute("sleep 20").expect('64 bytes', qaid="setupPC-tp")
        pc_01.execute("report setupPC-tp")

    # All assertions tracked under QAID setupPC-tp
    testbed.results.report("setupPC-tp")
