"""
Auto-generated pytest test for QAID 796400

Original DSL: ../testcase/ips/topology1/796400.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__796400(testbed):
    """
    Verify SSL MiTM: flow-based utm-profile can trigger mirror feature
    
    QAID: 796400
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Enable ssl mirror in firewall policy")
        fgt_a.execute("""
    config global
    config system fortiguard
    set protocol udp
    set port 8888
    end
        """)
        fgt_a.execute("end")
        helper_govdom1(fgt_a)
        fgt_a.execute("comment Edit webfilter profile to block Streaming Media and Download")
        fgt_a.execute("""
    config webfilter profile
    edit "web-filter-flow"
    config ftgd-wf
    config filters
    edit 100
    set category 25
    set action block
    next
    end
        """)
        fgt_a.execute("end")
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("comment Create decrypted-traffic-mirror profile")
        fgt_a.execute("""
    config firewall decrypted-traffic-mirror
    edit "ssl-mirror"
    set traffic-type ssl
    set traffic-source client
    set interface PORT4
    next
    end
        """)
        fgt_a.execute("comment Enable flow based dlp and flow based webfilter in firewall policy.")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set dlp-profile flow-dlp
    set webfilter-profile web-filter-flow
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    set np-acceleration disable
    set nat enable
    next
    end
        """)
        fgt_a.execute("sleep 5")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set decrypted-traffic-mirror ssl-mirror
    next
    end
        """)
        fgt_a.execute("comment Clear sys/ips sessions and all logs on disk")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("dia sniffer packet FGT_B:PORT4 'port 443' 4")
        fgt_b.execute("keep_running 1")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 5 https://PC_02:DESTINATION1/index.html --no-check-certificate")
        pc_02.execute("sleep 30")
        pc_02.execute("clear_buffer")
        pc_02.execute("comment Visit youtube to trigger webfilter profile")
        pc_02.execute("curl -v -4 -k https://www.youtube.com")
        pc_02.execute("sleep 20").expect('Web Page Blocked|SSL_ERROR_SYSCALL, errno 104|SYSCALL, errno = 104|SSL_read(.*?)errno', qaid="796400")
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("comment Check if ssl mirror is triggered and check webfilter log").expect('PC_02:IP_ETH1', qaid="796400")
        fgt_b.expect('.443', qaid="796400")
        fgt_b.execute("ctrl_c")
        fgt_b.execute("clear_buffer")
        fgt_b.execute("dia sniffer packet FGT_B:PORT4 'port 443' 4")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 3")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('web-filter-flow(.*?)blocked(.*?)Streaming Media and Download', qaid="796400")
        fgt_a.execute("exe log delete-all")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 5 https://PC_02:DESTINATION1/index.html --no-check-certificate")
        pc_02.execute("sleep 30")
        pc_02.execute("clear_buffer")
        pc_02.execute("comment Download an exe file to trigger dlp sensor")
        pc_02.execute("wget -t 1 -T 5 https://PC_02:DESTINATION1/app_data/bar.exe --no-check-certificate")
        pc_02.execute("sleep 10").expect('Connection reset by peer|Connection timed out', qaid="796400")
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("comment Check if ssl mirror is triggered and check dlp log").expect('PC_02:IP_ETH1', qaid="796400")
        fgt_b.expect('PC_05:IP_ETH1', qaid="796400")
        fgt_b.expect('.443', qaid="796400")
        fgt_b.execute("ctrl_c")
        fgt_b.execute("clear_buffer")
        fgt_b.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 9")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('block(.*?)flow-dlp', qaid="796400")
        fgt_a.execute("comment Clean up environment")
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset decrypted-traffic-mirror
    set utm-status disable
    unset np-acceleration
    set nat disable
    next
    end
        """)
        fgt_a.execute("""
    config firewall decrypted-traffic-mirror
    del "ssl-mirror"
    end
        """)
        fgt_a.execute("""
    config webfilter profile
    edit "web-filter-flow"
    config ftgd-wf
    config filters
    delete 100
    end
        """)
        fgt_a.execute("end")
        fgt_a.execute("next")
        fgt_a.execute("end")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 796400")

    # All assertions tracked under QAID 796400
    testbed.results.report("796400")
