"""
Auto-generated pytest test for QAID 826625

Original DSL: ../testcase/ips/topology1/826625.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__826625(testbed):
    """
    Verify by default "sync-session-ttl" enable in "config ips global"
    
    QAID: 826625
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    unset sync-session-ttl
    end
        """)
        fgt_a.execute("show full ips global")
        fgt_a.execute("sleep 2").expect('sync-session-ttl enable', qaid="826625")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 826625")

    # All assertions tracked under QAID 826625
    testbed.results.report("826625")
