"""
Auto-generated pytest test for QAID 796402

Original DSL: ../testcase/ips/topology1/796402.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__796402(testbed):
    """
    Verify SSL MiTM: ips/appctrl sensor can trigger mirror feature
    
    QAID: 796402
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set np-accel-mode none
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("comment Enable ssl mirror in firewall policy")
        helper_govdom1(fgt_a)
        fgt_a.execute("comment Create a new application list to block Video/Audio.")
        fgt_a.execute("""
    config application list
    edit "app-list-1"
    set other-application-log enable
    config entries
    edit 1
    set category 5
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("comment Create an IPS sensor to block eicar.")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("comment Create decrypted-traffic-mirror profile")
        fgt_a.execute("""
    config firewall decrypted-traffic-mirror
    edit "ssl-mirror"
    set traffic-type ssl
    set traffic-source client
    set interface PORT4
    next
    end
        """)
        fgt_a.execute("comment Enable ips sensor and application list in firewall policy.")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    set application-list "app-list-1"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    set np-acceleration disable
    next
    end
        """)
        fgt_a.execute("sleep 5")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set decrypted-traffic-mirror ssl-mirror
    next
    end
        """)
        fgt_a.execute("comment Clear sys/ips sessions and all logs on disk")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("dia sniffer packet PORT4 'port 443' 4")
        fgt_b.execute("keep_running 1")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 5 https://PC_02:DESTINATION1/index.html --no-check-certificate")
        pc_02.execute("sleep 30")
        pc_02.execute("clear_buffer")
        pc_02.execute("comment Download story.mp3 to trigger application list")
        pc_02.execute("curl -v -k https://PC_02:DESTINATION1/app_data/story.mp3")
        pc_02.execute("sleep 10").expect('100%', qaid="796402", should_fail=True)
    with testbed.device('PC_02_2') as pc_02_2:
        pc_02_2.execute("pkill curl")
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.expect('PC_02:IP_ETH1', qaid="796402")
        fgt_b.expect('PC_05:IP_ETH1', qaid="796402")
        fgt_b.expect('.443', qaid="796402")
        fgt_b.execute("ctrl_c")
        fgt_b.execute("clear_buffer")
        fgt_b.execute("dia sniffer packet PORT4 'port 443' 4")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 10")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('app-list-1(.*?)block(.*?)HTTP.Audio', qaid="796402")
        fgt_a.execute("exe log delete-all")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 5 https://PC_02:DESTINATION1/index.html --no-check-certificate")
        pc_02.execute("sleep 30")
        pc_02.execute("clear_buffer")
        pc_02.execute("comment Download eicar to trigger ips sensor")
        pc_02.execute("curl -vk -m 15 https://PC_02:DESTINATION1/virus/eicar")
        pc_02.execute("sleep 18").expect('timed out', qaid="796402")
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.expect('PC_02:IP_ETH1', qaid="796402")
        fgt_b.expect('PC_05:IP_ETH1', qaid="796402")
        fgt_b.expect('.443', qaid="796402")
        fgt_b.execute("ctrl_c")
        fgt_b.execute("clear_buffer")
        fgt_b.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('dropped(.*?)sensor-1(.*?)Eicar.Virus.Test.File', qaid="796402")
        fgt_a.execute("comment Clean up environment")
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset decrypted-traffic-mirror
    set utm-status disable
    unset np-acceleration
    next
    end
        """)
        fgt_a.execute("""
    config firewall decrypted-traffic-mirror
    del "ssl-mirror"
    end
        """)
        fgt_a.execute("""
    config application list
    delete "app-list-1"
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    unset np-accel-mode
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 796402")

    # All assertions tracked under QAID 796402
    testbed.results.report("796402")
