"""
Auto-generated pytest test for QAID 206022

Original DSL: ../testcase/ips/topology1/206022.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__206022(testbed):
    """
    This script will test below three test cases
    
    QAID: 206022
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    purge
    end
        """)
        fgt_a.execute("""
    config firewall interface-policy
    purge
    end
        """)
        fgt_a.execute("""
    config firewall interface-policy6
    purge
    end
        """)
        fgt_a.execute("""
    config firewall DoS-policy
    purge
    end
        """)
        fgt_a.execute("""
    config firewall DoS-policy6
    purge
    end
        """)
        fgt_a.execute("""
    config system zone
    edit "zone1"
    set intrazone deny
    set interface "PORT2" "vlan100"
    next
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "match small"
    set signature "F-SBID( --name \"match small\"; --attack_id 5835; --protocol tcp; --severity medium; --status disable; --default_action "clear_session"; --service http; --pattern \"small\"; )"
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 29844
    set rule 29844
    set status enable
    set action reset
    set log enable
    next
    edit 5835
    set rule 5835
    set status enable
    set action block
    set log enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set srcintf "zone1"
    set dstintf "PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set action accept
    set service "ALL"
    set schedule always
    set utm-status enable
    set ips-sensor "sensor-1"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 https://PC_02:DESTINATION1/index.html --no-check-certificate")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 15 http://PC_02:DESTINATION1/virus/eicar --no-check-certificate")
        pc_02.execute("sleep 20").expect('Connection reset by peer', qaid="206022")
        pc_02.execute("wget -t 1 -T 15 http://PC_02:DESTINATION1/ips_data/text --no-check-certificate")
        pc_02.execute("sleep 20").expect('Connection timed out', qaid="206022")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?)custom: match small', qaid="206022")
        fgt_a.expect('reset(.*?)Eicar.Virus.Test.File', qaid="206022")
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-1"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall DoS-policy
    edit "111"
    set interface zone1
    set srcaddr "all"
    set dstaddr "all"
    set service "ALL"
    config anomaly
    edit "icmp_flood"
    set status enable
    set action block
    set threshold 50
    set log enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips anomaly clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 30")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ping -f -q -c 100 PC_02:DESTINATION1")
        pc_01.execute("sleep 10").expect('[4-5]{1}\\[0,1,9]{1} received|[4-5]{1}\\[0,1,9]{1} packets received', qaid="206022")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 7")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('clear_session(.*?)anomaly: icmp_flood, 51 > threshold 50', qaid="206022")
        fgt_a.execute("""
    config firewall DoS-policy
    delete "111"
    end
        """)
        fgt_a.execute("""
    config firewall policy
    purge
    end
        """)
        fgt_a.execute("""
    config system zone
    del "zone1"
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set srcintf "PORT2"
    set dstintf "PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set action accept
    set service "ALL"
    set schedule always
    next
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 11
    set srcintf "PORT2"
    set dstintf "PORT1"
    set srcaddr6 "all"
    set dstaddr6 "all"
    set action accept
    set service "ALL"
    set schedule always
    next
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 206022")
        fgt_a.execute("report 206025")
        fgt_a.execute("report 206028")

    # All assertions tracked under QAID 206022
    testbed.results.report("206022")
