"""
Auto-generated pytest test for QAID 205921

Original DSL: ../testcase/ips/topology1/205921.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__205921(testbed):
    """
    IPS Regression Test Case 7.1
    
    QAID: 205921
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_7.1:Busy: no sensor need to be enabled")
        helper_govdom1(fgt_a)
        fgt_a.execute("diag sniffer packet any 'tcp and host PC_02:IP_ETH1 and host PC_05:IP_ETH1 ' 4")
        fgt_a.execute("keep_running 1")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("/home/tester/ips/attack_scripts/syn_fin PC_02:IP_ETH1 PC_05:IP_ETH1")
        pc_02.execute("keep_running 1")
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.expect('in PC_02:IP_ETH1', qaid="205921")
        fgt_a.execute("sleep 10").expect('out', qaid="205921", should_fail=True)
        fgt_a.execute("ctrl_c")
        fgt_a.execute("keep_running 0")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02_2') as pc_02_2:
        pc_02_2.execute("killall syn_fin")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("keep_running 0")
        pc_02.execute("report 205921")

    # All assertions tracked under QAID 205921
    testbed.results.report("205921")
