"""
Auto-generated pytest test for QAID 751046

Original DSL: ../testcase/ips/topology1/751046.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__751046(testbed):
    """
    Verify inline SSL inspection work for ips-sensor
    
    QAID: 751046
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Enable custom sig match small and Eicar on IPS sensor")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "match small"
    set signature "F-SBID( --name \"match small\"; --attack_id 5835; --protocol tcp; --severity medium; --status disable; --default_action clear_session; --service http;  --pattern \"small\"; )"
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set action block
    set log-packet enable
    set rule 5835 29844
    set status enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("diag ips raw clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 20 https://PC_02:DESTINATION1/index.html --no-check-certificate")
        pc_02.execute("sleep 30")
        pc_02.execute("curl -vk -m 20 https://PC_02:DESTINATION1/ips_data/text")
        pc_02.execute("sleep 22").expect('timed out', qaid="751046")
        pc_02.execute("curl -vk -m 20 https://PC_02:DESTINATION1/virus/eicar")
        pc_02.execute("sleep 22").expect('timed out', qaid="751046")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 4").expect('dropped(.*?)dstport=443(.*?)direction=\\"incoming\\"(.*?)Eicar.Virus.Test.File', qaid="751046")
        fgt_a.expect('dropped(.*?)dstport=443(.*?)direction=\\"incoming\\"(.*?)match small', qaid="751046")
        fgt_a.execute("comment Clean up environment")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config ips custom
    purge
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 751046")

    # All assertions tracked under QAID 751046
    testbed.results.report("751046")
