"""
Auto-generated pytest test for QAID 895497

Original DSL: ../testcase/ips/topology1/895497.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_goglobal import helper_goglobal


# ===== Test Function =====

def test__895497(testbed):
    """
    NGFW: verify that Botnet IP block and monitor is good
    
    QAID: 895497
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "ips-ngfw"
    set scan-botnet-connections block
    config entries
    edit 1
    set severity high
    set status enable
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall security-policy
    edit 99
    set utm-status enable
    set app-category 25
    set ips-sensor "ips-ngfw"
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("dia sys botnet-ip flush")
        fgt_a.execute("dia sys botnet-ip list 0 50 | grep 'port=80-80'")
        fgt_a.execute('setvar -e "ip=(.*?)-" -to IPADDR')
        fgt_a.execute("dia sys botnet-ip list 0 50 | grep 'port=80-80'")
        fgt_a.execute('setvar -e "botnet=(.*?), hit_count" -to RULEID')
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config router static
    edit 2
    set dst {$IPADDR} 255.255.255.0
    set gateway 172.16.200.2
    set device "PORT1"
    next
    end
        """)
        helper_outvdom(fgt_a)
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("""
    config system interface
    edit "loopback"
    set vdom "root"
    set ip {$IPADDR} 255.255.255.255
    set allowaccess ping https ssh snmp http telnet fgfm
    set type loopback
    next
    edit "PORT1"
    set mode static
    set vdom "root"
    set ip 172.16.200.2 255.255.255.0
    set allowaccess ping https ssh snmp http telnet fgfm
    set type physical
    next
    end
        """)
        fgt_b.execute("""
    config firewall policy
    edit 1
    set srcintf "PORT1"
    set dstintf "loopback"
    set action accept
    set srcaddr "all"
    set dstaddr "all"
    set schedule "always"
    set service "ALL"
    set nat enable
    next
    end
        """)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 20 https://PC_02:DESTINATION1 --no-check-certificate")
        pc_02.execute("sleep 22")
        pc_02.execute("clear_buffer")
        pc_02.execute(f"curl -v -m 5 http://{pc_02.testbed.env.get_dynamic_var('IPADDR')}")
        pc_02.execute("sleep 10").expect('Operation timed out', qaid="895497")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('botnet(.*?)dropped(.*?)ips-ngfw(.*?)', qaid="895497")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 2")
        fgt_a.execute("""
    config ips sensor
    edit "ips-ngfw"
    set scan-botnet-connections monitor
    next
    end
        """)
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 20 https://PC_02:DESTINATION1 --no-check-certificate")
        pc_02.execute("sleep 22")
        pc_02.execute("clear_buffer")
        pc_02.execute(f"curl -v -m 5 http://{pc_02.testbed.env.get_dynamic_var('IPADDR')}")
        pc_02.execute("sleep 10").expect('Operation timed out|Connection reset by peer|301 Moved|302 Found', qaid="895497")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('botnet(.*?)detected(.*?)ips-ngfw(.*?)', qaid="895497")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 2").expect('policyid=99(.*?)policytype=\\"security-policy(.*?)service=\\"HTTP(.*?)utmaction=\\"allow(.*?)countips=1', qaid="895497")
        fgt_a.execute("""
    config firewall security-policy
    edit 99
    unset ips-sensor
    unset app-category
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "ips-ngfw"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config router static
    del 2
    end
        """)
        helper_outvdom(fgt_a)
    with testbed.device('FGT_B') as fgt_b:
        fgt_b.execute("""
    config system interface
    edit "loopback"
    unset ip
    next
    edit "PORT1"
    unset ip
    next
    end
        """)
        fgt_b.execute("""
    config firewall policy
    del 1
    end
        """)
        fgt_b.execute("report 895497")

    # All assertions tracked under QAID 895497
    testbed.results.report("895497")
