"""
Auto-generated pytest test for QAID 819174

Original DSL: ../testcase/ips/topology1/819174.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__819174(testbed):
    """
    this is to check crash log after a bunch of test cases are run on FGT-A
    
    QAID: 819174
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia de crashlog read | grep firmware -A 100")
        fgt_a.execute("sleep 60").expect('application', qaid="819174", should_fail=True)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 819174")

    # All assertions tracked under QAID 819174
    testbed.results.report("819174")
