"""
Auto-generated pytest test for QAID 947031

Original DSL: ../testcase/ips/topology1/947031.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__947031(testbed):
    """
    947031: Verify CVE filter (id/wildcard) can be configured in IPS sensor
    
    QAID: 947031
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "g-cve"
    set comment "cve-GLOBAL"
    config entries
    edit 1
    set cve "cve-2010-0177"
    set status enable
    set log-packet enable
    set action block
    next
    edit 2
    set cve "CVE-2010"
    set action reset
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("show ips sensor g-cve").expect('cve-2010-0177', qaid="947031")
        fgt_a.expect('CVE-2010', qaid="947031")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "cve"
    set comment "cve-GLOBAL"
    config entries
    edit 1
    set cve "cve-2010-4091"
    set status enable
    set log-packet enable
    set action block
    next
    edit 2
    set cve "CVE-2010"
    set action reset
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("show ips sensor cve").expect('cve-2010-4091', qaid="947031")
        fgt_a.expect('CVE-2010', qaid="947031")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips sensor
    del "g-cve"
    end
        """)
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    del "cve"
    end
        """)
        fgt_a.execute("report 947031")

    # All assertions tracked under QAID 947031
    testbed.results.report("947031")
