"""
Auto-generated pytest test for QAID 853435

Original DSL: ../testcase/ips/topology1/853435.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__853435(testbed):
    """
    Transparent web proxy: verify that predefined signature detection is good via HTTP and HTTPS - HTTP GET
    
    QAID: 853435
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set inspection-mode proxy
    set http-policy-redirect enable
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action reset
    set log enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall proxy-policy
    edit 1
    set proxy transparent-web
    set srcintf "PORT2"
    set dstintf "PORT1"
    set srcaddr "all"
    set dstaddr "all"
    set service "webproxy"
    set action accept
    set schedule "always"
    set utm-status enable
    set ips-sensor "sensor-1"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 http://PC_02:DESTINATION1/index.html")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("curl -v http://PC_02:DESTINATION1/virus/eicar -m 15")
        pc_02.execute("sleep 20").expect('Intrusion Prevention Triggered', qaid="853435")
        pc_02.execute("curl -vk https://PC_02:DESTINATION1/virus/eicar -m 15")
        pc_02.execute("sleep 20").expect('Intrusion Prevention Triggered|transfer closed with 68 bytes remaining to read|Empty reply from server', qaid="853435")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 15")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('action=\\"reset(.*?)service=\\"HTTPS\\"(.*?)dstport=443(.*)Eicar.Virus.Test.File', qaid="853435")
        fgt_a.expect('action=\\"reset(.*?)service=\\"HTTP(.*?)Eicar.Virus.Test.File', qaid="853435")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('service=\\"HTTPS(.*?)policytype=\\"proxy-policy(.*?)utmaction=\\"reset(.*?)countips=1', qaid="853435")
        fgt_a.expect('service=\\"HTTP(.*?)policytype=\\"proxy-policy(.*?)utmaction=\\"reset(.*?)countips=1', qaid="853435")
        fgt_a.execute("""
    config firewall proxy-policy
    purge
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-1"
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset profile-protocol-options
    set utm-status disable
    unset inspection-mode
    next
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 853435")

    # All assertions tracked under QAID 853435
    testbed.results.report("853435")
