"""
Auto-generated pytest test for QAID 797094

Original DSL: ../testcase/ips/topology1/797094.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__797094(testbed):
    """
    Verify ips EICAR won't be detected when DSRI enable in firewall policy
    
    QAID: 797094
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Config IPS sensor and enable DSRI in firewall policy")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set profile-protocol-options "default"
    set ips-sensor "sensor-1"
    set dsri enable
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 --delete-after http://PC_02:DESTINATION1")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 20 --delete-after http://PC_02:DESTINATION1/virus/eicar")
        pc_02.execute("sleep 10").expect('68/68', qaid="797094")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('Eicar.Virus.Test.File', qaid="797094", should_fail=True)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set dsri disable
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        fgt_a.execute("sleep 30")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 --delete-after http://PC_02:DESTINATION1")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("wget -t 1 -T 5 --delete-after http://PC_02:DESTINATION1/virus/eicar")
        pc_02.execute("sleep 10").expect('Connection timed out', qaid="797094")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?)Eicar.Virus.Test.File', qaid="797094")
        fgt_a.execute("comment Clear environment")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    delete "sensor-1"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 797094")

    # All assertions tracked under QAID 797094
    testbed.results.report("797094")
