"""
Auto-generated pytest test for QAID 983980

Original DSL: ../testcase/ips/topology1/983980.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__983980(testbed):
    """
    983980: Verify with action pass, matched sctp traffic with specific ppid will be passed
    
    QAID: 983980
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config sctp-filter profile
    edit "sctp"
    set comment ''
    config ppid-filters
    edit 1
    set ppid 1773535488
    set action reset
    set comment 'test ppid'
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set sctp-filter-profile "sctp"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_05') as pc_05:
        pc_05.execute("python3 /root/server_sctp.py")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("python3 /root/client_sctp.py")
        pc_01.execute("sleep 10")
        pc_01.execute("clear_buffer")
    with testbed.device('PC_05_02') as pc_05_02:
        pc_05_02.execute("killall -9 python3")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 22")
        fgt_a.execute("exe log display").expect('sctp-filter(.*?)sctp-ppid-filter(.*?)action=\\"reset(.*)ppid=1773535488', qaid="983980")
        fgt_a.execute("exe log display").expect('sctp-filter(.*?)sctp-ppid-filter(.*?)action=\\"reset(.*)ppid=1773535488', qaid="983980")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display").expect('utmaction=\\"block(.*?)countsctpf=1', qaid="983980")
        fgt_a.execute("""
    config sctp-filter profile
    edit "sctp"
    config ppid-filters
    edit 1
    set action replace
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_05') as pc_05:
        pc_05.execute("python3 /root/server_sctp.py")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("python3 /root/client_sctp.py")
        pc_01.execute("sleep 10").expect('DLROW OLLEH', qaid="983980", should_fail=True)
        pc_01.execute("clear_buffer")
    with testbed.device('PC_05_02') as pc_05_02:
        pc_05_02.execute("killall -9 python3")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 22")
        fgt_a.execute("exe log display").expect('sctp-filter(.*?)sctp-ppid-filter(.*?)action=\\"replace(.*)ppid=1773535488', qaid="983980")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display").expect('utmaction=\\"block(.*?)countsctpf=1', qaid="983980")
        fgt_a.execute("""
    config sctp-filter profile
    edit "sctp"
    config ppid-filters
    edit 1
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_05') as pc_05:
        pc_05.execute("python3 /root/server_sctp.py")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("python3 /root/client_sctp.py")
        pc_01.execute("sleep 10").expect('DLROW OLLEH', qaid="983980")
        pc_01.execute("clear_buffer")
    with testbed.device('PC_05_02') as pc_05_02:
        pc_05_02.execute("killall -9 python3")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 22")
        fgt_a.execute("exe log display").expect('sctp-filter(.*?)sctp-ppid-filter(.*?)action=\\"pass(.*)ppid=1773535488', qaid="983980")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display").expect('utmaction=\\"allow(.*?)countsctpf=1', qaid="983980")
        fgt_a.execute("keep_running 0")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config sctp-filter profile
    del "sctp"
    end
        """)
        fgt_a.execute("report 983980")
        fgt_a.execute("report 983981")
        fgt_a.execute("report 983982")
        fgt_a.execute("report 983987")

    # All assertions tracked under QAID 983980
    testbed.results.report("983980")
