"""
Auto-generated pytest test for QAID 796389

Original DSL: ../testcase/ips/topology1/796389.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__796389(testbed):
    """
    Verify HTTP2 protocol: Appctrl-sensor detect/block well in firewall policy
    
    QAID: 796389
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set engine-count 1
    end
        """)
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config application list
    edit "app-list-1"
    set other-application-log enable
    config entries
    edit 1
    set category 2 5 6
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set application-list "app-list-1"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        fgt_a.execute("diag ips ssl clear")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 http://PC_02:DESTINATION1/index.html")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("curl -vk https://PC_02:DESTINATION1/app_data/story.mp3 -m 15")
        pc_02.execute("sleep 20").expect('GET \\/app_data\\/story.mp3 HTTP\\/2', qaid="796389")
        pc_02.expect('Operation timed out|Failed sending HTTP2 data', qaid="796389")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 15")
        fgt_a.execute("dia ips ssl status").expect('TLS 1.3: 1\\/1\\/0\\/0', qaid="796389")
        fgt_a.expect('HTTP\\/2:  1', qaid="796389")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 10")
        fgt_a.execute("exe log filter field dstip PC_05:IP_ETH1")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dstport=443(.*)service=\\"HTTPS(.*?)direction=\\"incoming(.*?)action=\\"block(.*?)app=\\"HTTP.Audio', qaid="796389")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('service=\\"HTTPS(.*?)app=\\"HTTP.Audio(.*?)utmaction=\\"block(.*?)countapp=3(.*?)utmref', qaid="796389")
        fgt_a.execute("""
    config application list
    edit "app-list-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        fgt_a.execute("diag ips ssl clear")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 http://PC_02:DESTINATION1/index.html")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("curl -vk https://PC_02:DESTINATION1/app_data/story.mp3 -m 15")
        pc_02.execute("sleep 20").expect('HTTP\\/2 200', qaid="796389")
        pc_02.expect('content-type: audio\\/mpeg', qaid="796389")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 15")
        fgt_a.execute("dia ips ssl status").expect('TLS 1.3: 1\\/1\\/0\\/0', qaid="796389")
        fgt_a.expect('HTTP\\/2:  1', qaid="796389")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 10")
        fgt_a.execute("exe log filter field dstip PC_05:IP_ETH1")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dstport=443(.*)service=\\"HTTPS(.*?)direction=\\"incoming(.*?)action=\\"pass(.*?)app=\\"HTTP.Audio', qaid="796389")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('service=\\"HTTPS(.*?)app=\\"HTTP.Audio(.*?)utmaction=\\"allow(.*?)countapp=3(.*?)utmref', qaid="796389")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config application list
    del "app-list-1"
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set engine-count 0
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 796389")

    # All assertions tracked under QAID 796389
    testbed.results.report("796389")
