"""
Auto-generated pytest test for QAID 711511

Original DSL: ../testcase/ips/topology1/711511.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__711511(testbed):
    """
    IPS Regression Test Case 10.2
    
    QAID: 711511
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_10.2:Busy: enable Winnuke.Windows.Out.Of.Band.Dos signature with action pass")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 29844
    set status enable
    set rule 29844
    set rate-count 3
    set rate-duration 60
    set rate-track src-ip
    set action block
    set log enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor "sensor-1"
    next
    edit 2
    set utm-status enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag ips share clear track_src_IP")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("route delete -net 172.16.200.0/24 gateway 10.10.10.1")
        pc_01.execute("wget -t 1 -T 25 http://PC_05:IP_ETH1")
        pc_01.execute("sleep 30")
        pc_01.execute("clear_buffer")
        pc_01.execute("wget -t 1 -T 5 http://PC_05:IP_ETH1/virus/eicar")
        pc_01.execute("sleep 10").expect('100%', qaid="711511")
        pc_01.execute("wget -t 1 -T 5 http://PC_05:IP_ETH1/virus/eicar")
        pc_01.execute("sleep 10").expect('100%', qaid="711511")
        pc_01.execute("wget -t 1 -T 5 http://PC_05:IP_ETH1/virus/eicar")
        pc_01.execute("sleep 10").expect('Connection timed out', qaid="711511")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('signature(.*?)dropped(.*?)Eicar.Virus.Test.File', qaid="711511")
        fgt_a.execute("keep_running 0")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    edit 2
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    delete 29844
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("report 711511")

    # All assertions tracked under QAID 711511
    testbed.results.report("711511")
