"""
Auto-generated pytest test for QAID 796399

Original DSL: ../testcase/ips/topology1/796399.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__796399(testbed):
    """
    Verify SSL MiTM: when the feature is enabled from the CLI a warning message (actual text to be supplied by legal) is to be displayed to the administrator that requires an affirmative acceptance before the feature is enabled
    
    QAID: 796399
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall decrypted-traffic-mirror
    edit "ssl-mirror"
    set traffic-type ssl
    set traffic-source client
    set interface PORT4
    next
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set ssl-ssh-profile "new-deep-inspection"
    myset decrypted-traffic-mirror ssl-mirror
        """).expect('THIS IS A LEGALLY BINDING AGREEMENT', qaid="796399")
        fgt_a.expect('Do you want to continue', qaid="796399")
        fgt_a.execute("y")
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("show firewall policy 1")
        fgt_a.execute("sleep 2").expect('set decrypted-traffic-mirror \\"ssl-mirror\\"', qaid="796399")
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset decrypted-traffic-mirror
    next
    end
        """)
        fgt_a.execute("""
    config firewall decrypted-traffic-mirror
    del "ssl-mirror"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 796399")

    # All assertions tracked under QAID 796399
    testbed.results.report("796399")
