"""
Auto-generated pytest test for QAID 206024

Original DSL: ../testcase/ips/topology1/206024.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__206024(testbed):
    """
    IPS Regression Test Case 19.5
    
    QAID: 206024
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_19.5:Busy: create custom signatures match_apache")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "match apache"
    set signature "F-SBID( --attack_id 5022;  --name \"match Apache\"; --default_action reset; --service http; --protocol tcp; --pattern \"Apache\";--severity info; --status disable; )"
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 5022
    set rule 5022
    set status enable
    set action pass
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall interface-policy
    edit 1
    set interface "vlan100"
    set srcaddr "all"
    set dstaddr "all"
    set service "ALL"
    set ips-sensor-status enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("route add -host 172.16.200.55 gw 10.10.10.1")
        pc_01.execute("sleep 2")
        pc_01.execute("wget -t 1 -T 20 -S --delete-after http://172.16.200.55/index.html")
        pc_01.execute("sleep 25")
        pc_01.execute("wget -t 1 -T 20 -S --delete-after http://172.16.200.55/ips_data/text")
        pc_01.execute("sleep 22").expect('100%', qaid="206024")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('detected.*attackid=5022.*custom: match Apache', qaid="206024")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 5022
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 20 -S --delete-after http://172.16.200.55/index.html")
        pc_01.execute("sleep 25")
        pc_01.execute("wget -t 1 -T 20 -S --delete-after 172.16.200.55/ips_data/text")
        pc_01.execute("sleep 22").expect('timed out', qaid="206024")
        pc_01.execute("route del -host 172.16.200.55 gw 10.10.10.1")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped.*attackid=5022.*custom: match Apache', qaid="206024")
        fgt_a.execute("""
    config firewall interface-policy
    delete 1
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    delete 5022
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config ips custom
    delete "match apache"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 206024")

    # All assertions tracked under QAID 206024
    testbed.results.report("206024")
