"""
Auto-generated pytest test for QAID 205972

Original DSL: ../testcase/ips/topology1/205972.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__205972(testbed):
    """
    Verify signature match is checked in order when multiple filters are defined in a sensor
    
    QAID: 205972
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Configure IPS sensor with two filters including all icmp based signatures")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set protocol ICMP
    set status enable
    set action pass
    set log enable
    next
    edit 2
    set protocol ICMP
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set profile-protocol-options "default"
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping -c 10 PC_02:DESTINATION1")
        pc_02.execute("sleep 15")
        pc_02.execute("clear_buffer")
        pc_02.execute("ping -c 10 -s 45000 PC_02:DESTINATION1")
        pc_02.execute("sleep 15").expect('45008 bytes', qaid="205972")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('detected(.*?)ICMP.Oversized.Packet', qaid="205972")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 5")
        fgt_a.execute("comment Delete the 1st filter in ips sensor")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    delete 1
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 10")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("sleep FGT_A:SLEEP_TIMER")
        pc_02.execute("ping -c 5 -s 45000 PC_02:DESTINATION1")
        pc_02.execute("sleep 10").expect('0 received|0 packets received', qaid="205972")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?)ICMP.Oversized.Packet', qaid="205972")
        fgt_a.execute("comment Clean up environment")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    delete "sensor-1"
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 205972")

    # All assertions tracked under QAID 205972
    testbed.results.report("205972")
