"""
Auto-generated pytest test for QAID 206088

Original DSL: ../testcase/ips/topology1/206088.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__206088(testbed):
    """
    IPS Regression Test Case 26.3
    
    QAID: 206088
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_26.3:Busy: block large_icmp signature with quarantine attacker")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    sleep 5
    edit "111"
    set status enable
    set log enable
    set action block
    set quarantine attacker
    set quarantine-expiry 3m
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm enable
    set ips-sensor "sensor-1"
    next
    end
        """)
        fgt_a.execute("dia user banned-ip clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ping -c 5 PC_01:DESTINATION1")
        pc_01.execute("sleep 20")
        pc_01.execute("clear_buffer")
        pc_01.execute("wget -t 1 -T 25 http://PC_01:DESTINATION1/index.html")
        pc_01.execute("sleep 30")
        pc_01.execute("clear_buffer")
        pc_01.execute("ping -s 45000 -c 5 PC_01:DESTINATION1").expect('0 received|0 packets received', qaid="206088")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('dropped(.*?) ICMP.Oversized.Packet', qaid="206088")
        fgt_a.execute("sleep 7")
        fgt_a.execute("dia user banned-ip list")
        fgt_a.execute("sleep 2").expect('172.16.200.11(.*)IPS', qaid="206088")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ping -c 1 PC_01:DESTINATION1").expect('0 received|0 packets received', qaid="206088")
        pc_01.execute("ping -c 1 172.16.200.3").expect('0 received|0 packets received', qaid="206088")
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("sleep 5")
        pc_02.execute("ping -c 1 PC_01:DESTINATION1").expect('64 bytes', qaid="206088")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia user banned-ip clear")
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    delete "111"
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("report 206088")

    # All assertions tracked under QAID 206088
    testbed.results.report("206088")
