"""
Auto-generated pytest test for QAID 833686

Original DSL: ../testcase/ips/topology1/833686.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__833686(testbed):
    """
    Verify CLIENT: wanopt policy have good utm and traffic-log for AppCtrl
    
    QAID: 833686
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Create application list to block HTTP.Audio and add this list to firewall policy")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config application list
    edit "app-list-1"
    config entries
    edit 1
    set category 5
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set srcintf "PORT2"
    set dstintf "PORT3"
    set srcaddr "all"
    set dstaddr "all"
    set action accept
    set schedule "always"
    set service "ALL"
    set utm-status enable
    set application-list "app-list-1"
    set profile-protocol-options "default"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("curl -vk https://PC_02:DESTINATION1/app_data/story.mp3")
        pc_01.execute("sleep 15").expect('Application Blocked', qaid="833686")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 10")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('HTTPS(.*?)app-list-1(.*?)block(.*?)HTTP.Audio', qaid="833686")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('service=\\"HTTPS(.*?)utmaction=\\"block(.*?)countapp', qaid="833686")
        fgt_a.execute("""
    config application list
    edit "app-list-1"
    config entries
    edit 1
    unset category
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset application-list
    next
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 833686")

    # All assertions tracked under QAID 833686
    testbed.results.report("833686")
