"""
Auto-generated pytest test for QAID 796386

Original DSL: ../testcase/ips/topology1/796386.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__796386(testbed):
    """
    Verify HTTP2 protocol:flow-av can detect/block virus in firewall policy
    
    QAID: 796386
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set engine-count 1
    end
        """)
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config antivirus profile
    edit "flow-av"
    config http
    set av-scan monitor
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set av-profile "flow-av"
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag ips ssl clear")
        fgt_a.execute("dia ips av cache clear")
        fgt_a.execute("dia antivirus quarantine purge")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("curl -vk https://PC_02:DESTINATION1/virus/eicar -m 15")
        pc_02.execute("sleep 20").expect('HTTP\\/2 200', qaid="796386")
        pc_02.expect('EICAR-STANDARD-ANTIVIRUS-TEST-FILE', qaid="796386")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 15")
        fgt_a.execute("dia ips ssl status")
        fgt_a.execute("sleep 1").expect('TLS 1.3: 1\\/1\\/0\\/0', qaid="796386")
        fgt_a.expect('HTTP\\/2:  1', qaid="796386")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 2")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('action=\\"monitored(.*?)service=\\"HTTPS(.*?)dstport=443(.*)direction=\\"incoming(.*?)filename=\\"eicar(.*?)virus=\\"EICAR_TEST_FILE', qaid="796386")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('service=\\"HTTPS(.*?)utmaction=\\"allow(.*?)countav=1(.*?)utmref', qaid="796386")
        fgt_a.execute("""
    config antivirus profile
    edit "flow-av"
    config http
    set av-scan block
    set quarantine enable
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        fgt_a.execute("dia ips av cache clear")
        fgt_a.execute("diag ips ssl clear")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 http://PC_02:DESTINATION1/index.html")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("curl -vk https://PC_02:DESTINATION1/virus/eicar.exe -m 15 -O")
        pc_02.execute("sleep 20").expect('GET \\/virus\\/eicar.exe HTTP\\/2', qaid="796386")
        pc_02.expect('Failed receiving HTTP2 data|Failed sending HTTP2 data', qaid="796386")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 15")
        fgt_a.execute("dia ips ssl status")
        fgt_a.execute("sleep 1").expect('TLS 1.3: 1\\/1\\/0\\/0', qaid="796386")
        fgt_a.expect('HTTP\\/2:  1', qaid="796386")
        fgt_a.execute("dia antivirus quarantine list").expect('eicar', qaid="796386")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 2")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('action=\\"blocked(.*?)service=\\"HTTPS(.*?)dstport=443(.*)direction=\\"incoming(.*?)virus=\\"EICAR_TEST_FILE', qaid="796386")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('service=\\"HTTPS(.*?)utmaction=\\"block(.*?)countav=1(.*?)utmref', qaid="796386")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config antivirus profile
    del "flow-av"
    end
        """)
        fgt_a.execute("dia ips av cache clear")
        fgt_a.execute("dia antivirus quarantine purge")
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set engine-count 0
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 796386")

    # All assertions tracked under QAID 796386
    testbed.results.report("796386")
