"""
Auto-generated pytest test for QAID 796392

Original DSL: ../testcase/ips/topology1/796392.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_goglobal import helper_goglobal
from helpers.helper_outvdom import helper_outvdom
from helpers.helper_govdom1 import helper_govdom1


# ===== Test Function =====

def test__796392(testbed):
    """
    Verify HTTP2 protocol: IPS-sensor detect/block well in firewall policy
    
    QAID: 796392
    """
    with testbed.device('FGT_A') as fgt_a:
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set engine-count 1
    end
        """)
        helper_outvdom(fgt_a)
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips custom
    edit "match small"
    set signature "F-SBID( --name \"match small \"; --attack_id 5835; --protocol tcp; --severity medium; --status disable; --default_action drop; --service http;  --pattern \"small\"; --context file; )"
    set comment ''
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action pass
    set log enable
    next
    edit 2
    set rule 5835
    set status enable
    set action block
    set log enable
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status enable
    set ips-sensor sensor-1
    set ssl-ssh-profile "new-deep-inspection"
    next
    end
        """)
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep FGT_A:SLEEP_TIMER")
        fgt_a.execute("diag ips ssl clear")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("wget -t 1 -T 15 http://PC_02:DESTINATION1/index.html")
        pc_02.execute("sleep 20")
        pc_02.execute("clear_buffer")
        pc_02.execute("curl -vk https://PC_02:DESTINATION1/virus/eicar -m 15")
        pc_02.execute("sleep 20").expect('HTTP\\/2 200', qaid="796392")
        pc_02.expect('EICAR-STANDARD-ANTIVIRUS-TEST-FILE', qaid="796392")
        pc_02.execute("curl -vk https://PC_02:DESTINATION1/ips_data/text -m 15")
        pc_02.execute("sleep 20").expect('SSL_write(.*?)errno|Operation timed out', qaid="796392")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia ips session clear")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 15")
        fgt_a.execute("dia ips ssl status").expect('TLS 1.3: 2\\/2\\/0\\/0', qaid="796392")
        fgt_a.expect('HTTP\\/2:  2', qaid="796392")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('action=\\"dropped(.*?)service=\\"HTTPS(.*?)dstport=443(.*)direction=\\"incoming(.*?)custom: match small', qaid="796392")
        fgt_a.expect('action=\\"detected(.*?)service=\\"HTTPS(.*?)dstport=443(.*?)direction=\\"incoming(.*?)Eicar.Virus.Test.File', qaid="796392")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('service=\\"HTTPS(.*?)utmaction=\\"block(.*?)countips=1', qaid="796392")
        fgt_a.expect('service=\\"HTTPS(.*?)utmaction=\\"allow(.*?)countips=1', qaid="796392")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    del "sensor-1"
    end
        """)
        fgt_a.execute("""
    config firewall policy
    edit 1
    set utm-status disable
    next
    end
        """)
        helper_outvdom(fgt_a)
        helper_goglobal(fgt_a)
        fgt_a.execute("""
    config ips global
    set engine-count 0
    end
        """)
        helper_outvdom(fgt_a)
        fgt_a.execute("report 796392")

    # All assertions tracked under QAID 796392
    testbed.results.report("796392")
