"""
Auto-generated pytest test for QAID 741646

Original DSL: ../testcase/ips/topology1/741646.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__741646(testbed):
    """
    Verify CLIENT: ips sensor can detect SSL traffic(https) signature when it's in wanopt tunnel
    
    QAID: 741646
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment Create ips sensor to block eicar and add this sensor to firewall policy")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    edit 1
    set rule 29844
    set status enable
    set action block
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("""
    config firewall policy
    edit 1
    set srcintf "PORT2"
    set dstintf "PORT3"
    set srcaddr "all"
    set dstaddr "all"
    set action accept
    set schedule "always"
    set service "ALL"
    set utm-status enable
    set ips-sensor "sensor-1"
    set ssl-ssh-profile "new-deep-inspection"
    set profile-protocol-options "default"
    next
    end
        """)
        fgt_a.execute("diag ips session clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 25")
        fgt_a.execute("comment Clear wad statistics")
        fgt_a.execute("sleep 5")
        helper_outvdom(fgt_a)
        fgt_a.execute("comment Download eicar via http")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("wget -t 1 -T 5 https://PC_02:DESTINATION1/virus/eicar --no-check-certificate")
        pc_01.execute("sleep 15").expect('Giving up|403 Forbidden', qaid="741646")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("comment Check IPS and traffic log")
        fgt_a.execute("dia sys session clear")
        fgt_a.execute("sleep 5")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('dropped(.*?)Eicar.Virus.Test.File', qaid="741646")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 4")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('dropped(.*?)Eicar.Virus.Test.File', qaid="741646")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 0")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 5").expect('dstport=443(.*?)utmaction=\\"block(.*?)countips=1', qaid="741646")
        fgt_a.execute("comment Clean up environment")
        fgt_a.execute("""
    config firewall policy
    edit 1
    unset ips-sensor
    next
    end
        """)
        fgt_a.execute("""
    config ips sensor
    edit "sensor-1"
    config entries
    purge
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        helper_outvdom(fgt_a)
        fgt_a.execute("report 741646")
        fgt_a.execute("report 751049")

    # All assertions tracked under QAID 741646
    testbed.results.report("741646")
