"""
Auto-generated pytest test for QAID 206075

Original DSL: ../testcase/ips/topology1/206075.txt
Generated by: DSL Transpiler
"""

import pytest
from pathlib import Path
import sys

# Add fluent API to path (go up to prototype directory)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'fluent_api'))

from fluent import TestBed

# Import helper functions from helpers
sys.path.insert(0, str(Path(__file__).parent))
from helpers.helper_govdom1 import helper_govdom1
from helpers.helper_outvdom import helper_outvdom


# ===== Test Function =====

def test__206075(testbed):
    """
    IPS Regression Test Case 24.20
    
    QAID: 206075
    """
    with testbed.device('FGT_A') as fgt_a:
        fgt_a.execute("comment REGR_IPS_24.20:Busy: enable DoS sensor")
        helper_govdom1(fgt_a)
        fgt_a.execute("""
    config firewall DoS-policy
    edit "111"
    set interface FGT_A:PORT2
    set srcaddr "all"
    set dstaddr "all"
    set service "ALL"
    config anomaly
    edit "icmp_flood"
    set status enable
    set log enable
    set action block
    set quarantine attacker
    set quarantine-expiry 3m
    set threshold 10
    next
    end
        """)
        fgt_a.execute("next")
        fgt_a.execute("end")
        fgt_a.execute("dia user banned-ip clear")
        fgt_a.execute("diag sys session clear")
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 7")
        fgt_a.execute("exe log delete-all")
        fgt_a.execute("sleep 22")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping -f -c 100 PC_02:DESTINATION1").expect('10 received|10 packets received', qaid="206075")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("exe log filter device FGT_A:LOG_DEVICE")
        fgt_a.execute("exe log filter category 7")
        fgt_a.execute("exe log display")
        fgt_a.execute("sleep 3").expect('clear_session(.*?)anomaly: icmp_flood, 11 > threshold 10', qaid="206075")
        fgt_a.execute("dia user banned-ip list")
        fgt_a.execute("sleep 2").expect('PC_02:IP_ETH1', qaid="206075")
        helper_outvdom(fgt_a)
    with testbed.device('PC_02') as pc_02:
        pc_02.execute("ping -c 1 PC_02:DESTINATION1").expect('0 received|0 packets received', qaid="206075")
    with testbed.device('PC_01') as pc_01:
        pc_01.execute("ping -c 3 PC_02:DESTINATION1").expect('64 bytes', qaid="206075")
    with testbed.device('FGT_A') as fgt_a:
        helper_govdom1(fgt_a)
        fgt_a.execute("dia user banned-ip clear")
        fgt_a.execute("sleep 3")
        fgt_a.execute("""
    config firewall DoS-policy
    delete 111
    end
        """)
        fgt_a.execute("report 206075")

    # All assertions tracked under QAID 206075
    testbed.results.report("206075")
